XProto Framework API Document: x3::InfoMessage Class Reference
x3::InfoMessage Class Reference
#include <x3.pb.h>
Public Member Functions
InfoMessage ()
virtual ~InfoMessage ()
InfoMessage (const InfoMessage &from)
InfoMessage & operator= (const InfoMessage &from)
void Swap (InfoMessage *other)
InfoMessage * New () const
InfoMessage * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const InfoMessage &from)
void MergeFrom (const InfoMessage &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
bool has_status_ () const
void clear_status_ ()
const ::x3::Status & status_ () const
::x3::Status * mutable_status_ ()
::x3::Status * release_status_ ()
void set_allocated_status_ (::x3::Status *status_)
bool has_command_ () const
void clear_command_ ()
const ::x3::Command & command_ () const
::x3::Command * mutable_command_ ()
::x3::Command * release_command_ ()
void set_allocated_command_ (::x3::Command *command_)
bool has_loglevel_ () const
void clear_loglevel_ ()
const ::x3::LogLevel & loglevel_ () const
::x3::LogLevel * mutable_loglevel_ ()
::x3::LogLevel * release_loglevel_ ()
void set_allocated_loglevel_ (::x3::LogLevel *loglevel_)
bool has_response_ () const
void clear_response_ ()
const ::x3::Response & response_ () const
::x3::Response * mutable_response_ ()
::x3::Response * release_response_ ()
void set_allocated_response_ (::x3::Response *response_)
int config__size () const
void clear_config_ ()
const ::x3::Config & config_ (int index) const
::x3::Config * mutable_config_ (int index)
::x3::Config * add_config_ ()
::google::protobuf::RepeatedPtrField
< ::x3::Config > * mutable_config_ ()
const
::google::protobuf::RepeatedPtrField
< ::x3::Config > & config_ () const
int version__size () const
void clear_version_ ()
const ::x3::Version & version_ (int index) const
::x3::Version * mutable_version_ (int index)
::x3::Version * add_version_ ()
::google::protobuf::RepeatedPtrField
< ::x3::Version > * mutable_version_ ()
const
::google::protobuf::RepeatedPtrField
< ::x3::Version > & version_ () const
int capability__size () const
void clear_capability_ ()
const ::x3::Capability & capability_ (int index) const
::x3::Capability * mutable_capability_ (int index)
::x3::Capability * add_capability_ ()
::google::protobuf::RepeatedPtrField
< ::x3::Capability > * mutable_capability_ ()
const
::google::protobuf::RepeatedPtrField
< ::x3::Capability > & capability_ () const
Static Public Member Functions
static const InfoMessage & default_instance ()
Static Public Attributes
static const int kStatusFieldNumber = 1
static const int kCommandFieldNumber = 2
static const int kLoglevelFieldNumber = 3
static const int kResponseFieldNumber = 4
static const int kConfigFieldNumber = 5
static const int kVersionFieldNumber = 6
static const int kCapabilityFieldNumber = 7
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (InfoMessage *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::x3::Status * status__
::x3::Command * command__
::x3::LogLevel * loglevel__
::x3::Response * response__
::google::protobuf::RepeatedPtrField
< ::x3::Config > config__
::google::protobuf::RepeatedPtrField
< ::x3::Version > version__
::google::protobuf::RepeatedPtrField
< ::x3::Capability > capability__
int _cached_size_
Static Private Attributes
static InfoMessage * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 3812 of file x3.pb.h.
Constructor & Destructor Documentation
x3::InfoMessage::InfoMessage ()
Definition at line 12659 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.InfoMessage)
 }
x3::InfoMessage::~InfoMessage () virtual
Definition at line 12710 of file x3.pb.cc.
{
   // @@protoc_insertion_point(destructor:x3.InfoMessage)
   SharedDtor();
 }
x3::InfoMessage::InfoMessage (const InfoMessage & from)
Definition at line 12693 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.InfoMessage)
 }
Member Function Documentation
x3::Capability * x3::InfoMessage::add_capability_ () inline
Definition at line 8378 of file x3.pb.h.
Referenced by MergePartialFromCodedStream().
{
   // @@protoc_insertion_point(field_add:x3.InfoMessage.capability_)
   return capability__.Add();
 }
x3::Config * x3::InfoMessage::add_config_ () inline
Definition at line 8318 of file x3.pb.h.
Referenced by MergePartialFromCodedStream().
{
   // @@protoc_insertion_point(field_add:x3.InfoMessage.config_)
   return config__.Add();
 }
x3::Version * x3::InfoMessage::add_version_ () inline
Definition at line 8348 of file x3.pb.h.
Referenced by MergePartialFromCodedStream().
{
   // @@protoc_insertion_point(field_add:x3.InfoMessage.version_)
   return version__.Add();
 }
int x3::InfoMessage::ByteSize () const
Definition at line 12946 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.InfoMessage)
   int total_size = 0;
   // optional .x3.Status status_ = 1;
   if (this->has_status_()) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         *this->status__);
   }
   // optional .x3.Command command_ = 2;
   if (this->has_command_()) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         *this->command__);
   }
   // optional .x3.LogLevel loglevel_ = 3;
   if (this->has_loglevel_()) {
     total_size += 1 +