XProto Framework API Document: x3::Config Class Reference
x3::Config Class Reference
#include <x3.pb.h>
Public Member Functions
Config ()
virtual ~Config ()
Config (const Config &from)
Config & operator= (const Config &from)
void Swap (Config *other)
Config * New () const
Config * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const Config &from)
void MergeFrom (const Config &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_type_ ()
const ::std::string & type_ () const
void set_type_ (const ::std::string &value)
void set_type_ (const char *value)
void set_type_ (const char *value, size_t size)
::std::string * mutable_type_ ()
::std::string * release_type_ ()
void set_allocated_type_ (::std::string *type_)
int threshold__size () const
void clear_threshold_ ()
const ::x3::Threshold & threshold_ (int index) const
::x3::Threshold * mutable_threshold_ (int index)
::x3::Threshold * add_threshold_ ()
::google::protobuf::RepeatedPtrField
< ::x3::Threshold > * mutable_threshold_ ()
const
::google::protobuf::RepeatedPtrField
< ::x3::Threshold > & threshold_ () const
int mode__size () const
void clear_mode_ ()
const ::x3::Mode & mode_ (int index) const
::x3::Mode * mutable_mode_ (int index)
::x3::Mode * add_mode_ ()
::google::protobuf::RepeatedPtrField
< ::x3::Mode > * mutable_mode_ ()
const
::google::protobuf::RepeatedPtrField
< ::x3::Mode > & mode_ () const
int shield__size () const
void clear_shield_ ()
const ::x3::Box & shield_ (int index) const
::x3::Box * mutable_shield_ (int index)
::x3::Box * add_shield_ ()
::google::protobuf::RepeatedPtrField
< ::x3::Box > * mutable_shield_ ()
const
::google::protobuf::RepeatedPtrField
< ::x3::Box > & shield_ () const
Static Public Member Functions
static const Config & default_instance ()
Static Public Attributes
static const int kTypeFieldNumber = 1
static const int kThresholdFieldNumber = 2
static const int kModeFieldNumber = 3
static const int kShieldFieldNumber = 4
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (Config *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::internal::ArenaStringPtr type__
::google::protobuf::RepeatedPtrField
< ::x3::Threshold > threshold__
::google::protobuf::RepeatedPtrField
< ::x3::Mode > mode__
::google::protobuf::RepeatedPtrField
< ::x3::Box > shield__
int _cached_size_
Static Private Attributes
static Config * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 3155 of file x3.pb.h.
Constructor & Destructor Documentation
x3::Config::Config ()
Definition at line 10744 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.Config)
 }
x3::Config::~Config () virtual
Definition at line 10769 of file x3.pb.cc.
                 {
   // @@protoc_insertion_point(destructor:x3.Config)
   SharedDtor();
 }
x3::Config::Config (const Config & from)
Definition at line 10754 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.Config)
 }
Member Function Documentation
x3::Mode * x3::Config::add_mode_ () inline
Definition at line 7796 of file x3.pb.h.
Referenced by MergePartialFromCodedStream().
{
   // @@protoc_insertion_point(field_add:x3.Config.mode_)
   return mode__.Add();
 }
x3::Box * x3::Config::add_shield_ () inline
Definition at line 7826 of file x3.pb.h.
Referenced by MergePartialFromCodedStream().
{
   // @@protoc_insertion_point(field_add:x3.Config.shield_)
   return shield__.Add();
 }
x3::Threshold * x3::Config::add_threshold_ () inline
Definition at line 7766 of file x3.pb.h.
Referenced by MergePartialFromCodedStream().
{
   // @@protoc_insertion_point(field_add:x3.Config.threshold_)
   return threshold__.Add();
 }
int x3::Config::ByteSize () const
Definition at line 10946 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.Config)
   int total_size = 0;
   // optional string type_ = 1;
   if (this->type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->type_());
   }
   // repeated .x3.Threshold threshold_ = 2;
   total_size += 1 * this->threshold__size();
   for (int i = 0; i < this->threshold__size(); i++) {
     total_size +=
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         this->threshold_(i));
   }
   // repeated .x3.Mode mode_ = 3;
   total_size += 1 * this->mode__size();
   for (int i = 0; i < this->mode__size(); i++) {
     total_size +=
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         this->mode_(i));
   }
   // repeated .x3.Box shield_ = 4;
   total_size += 1 * this->shield__size();
   for (int i = 0; i < this->shield__size(); i++) {
     total_size +=
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         this->shield_(i));
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::Config::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 10987 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const Config*>(&from));
 }
void x3::Config::Clear ()
Definition at line 10808 of file x3.pb.cc.
Referenced by CopyFrom().
                    {
 // @@protoc_insertion_point(message_clear_start:x3.Config)
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   threshold__.Clear();
   mode__.Clear();
   shield__.Clear();
 }