XProto Framework API Document: x3::Addition Class Reference
x3::Addition Class Reference
#include <x3.pb.h>
Public Member Functions
Addition ()
virtual ~Addition ()
Addition (const Addition &from)
Addition & operator= (const Addition &from)
void Swap (Addition *other)
Addition * New () const
Addition * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const Addition &from)
void MergeFrom (const Addition &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
bool has_check_ () const
void clear_check_ ()
const ::x3::Check & check_ () const
::x3::Check * mutable_check_ ()
::x3::Check * release_check_ ()
void set_allocated_check_ (::x3::Check *check_)
bool has_frame_ () const
void clear_frame_ ()
const ::x3::Frame & frame_ () const
::x3::Frame * mutable_frame_ ()
::x3::Frame * release_frame_ ()
void set_allocated_frame_ (::x3::Frame *frame_)
Static Public Member Functions
static const Addition & default_instance ()
Static Public Attributes
static const int kCheckFieldNumber = 1
static const int kFrameFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (Addition *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::x3::Check * check__
::x3::Frame * frame__
int _cached_size_
Static Private Attributes
static Addition * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 4203 of file x3.pb.h.
Constructor & Destructor Documentation
x3::Addition::Addition ()
Definition at line 13925 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.Addition)
 }
x3::Addition::~Addition () virtual
Definition at line 13962 of file x3.pb.cc.
                     {
   // @@protoc_insertion_point(destructor:x3.Addition)
   SharedDtor();
 }
x3::Addition::Addition (const Addition & from)
Definition at line 13947 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.Addition)
 }
Member Function Documentation
int x3::Addition::ByteSize () const
Definition at line 14084 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.Addition)
   int total_size = 0;
   // optional .x3.Check check_ = 1;
   if (this->has_check_()) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         *this->check__);
   }
   // optional .x3.Frame frame_ = 2;
   if (this->has_frame_()) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         *this->frame__);
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
const ::x3::Check & x3::Addition::check_ () const inline
Definition at line 8510 of file x3.pb.h.
Referenced by MergeFrom(), and set_allocated_check_().
{
   // @@protoc_insertion_point(field_get:x3.Addition.check_)
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   return check__ != NULL ? *check__ : *default_instance().check__;
 #else
   return check__ != NULL ? *check__ : *default_instance_->check__;
 #endif
 }
void x3::Addition::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 14108 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const Addition*>(&from));
 }
void x3::Addition::Clear ()
Definition at line 14002 of file x3.pb.cc.
Referenced by CopyFrom().
                      {
 // @@protoc_insertion_point(message_clear_start:x3.Addition)
   if (GetArenaNoVirtual() == NULL && check__ != NULL) delete check__;
   check__ = NULL;
   if (GetArenaNoVirtual() == NULL && frame__ != NULL) delete frame__;
   frame__ = NULL;
 }
void x3::Addition::clear_check_ () inline
Definition at line 8506 of file x3.pb.h.
{
   if (GetArenaNoVirtual() == NULL && check__ != NULL) delete check__;
   check__ = NULL;
 }
void x3::Addition::clear_frame_ () inline
Definition at line 8548 of file x3.pb.h.
{
   if (GetArenaNoVirtual() == NULL && frame__ != NULL) delete frame__;
   frame__ = NULL;
 }
void x3::Addition::CopyFrom (const Addition & from)
Definition at line 14126 of file x3.pb.cc.
Referenced by operator=().
{
 // @@protoc_insertion_point(class_specific_copy_from_start:x3.Addition)
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
const Addition & x3::Addition::default_instance () static
Definition at line 13983 of file x3.pb.cc.
Referenced by check_(), frame_(), x3::MessagePack::InitAsDefaultInstance(), and SharedDtor().
{
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   protobuf_AddDesc_x3_2eproto();
 #else
   if (default_instance_ == NULL) protobuf_AddDesc_x3_2eproto();
 #endif
   return *default_instance_;
 }
void x3::Addition::DiscardUnknownFields ()
const ::x3::Frame & x3::Addition::frame_ () const inline
Definition at line 8552 of file x3.pb.h.
Referenced by MergeFrom(), and set_allocated_frame_().
{
   // @@protoc_insertion_point(field_get:x3.Addition.frame_)
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   return frame__ != NULL ? *frame__ : *default_instance().frame__;
 #else
   return frame__ != NULL ? *frame__ : *default_instance_->frame__;
 #endif
 }