XProto Framework API Document: x3::Mode Class Reference
x3::Mode Class Reference
#include <x3.pb.h>
Public Member Functions
Mode ()
virtual ~Mode ()
Mode (const Mode &from)
Mode & operator= (const Mode &from)
void Swap (Mode *other)
Mode * New () const
Mode * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const Mode &from)
void MergeFrom (const Mode &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_type_ ()
const ::std::string & type_ () const
void set_type_ (const ::std::string &value)
void set_type_ (const char *value)
void set_type_ (const char *value, size_t size)
::std::string * mutable_type_ ()
::std::string * release_type_ ()
void set_allocated_type_ (::std::string *type_)
void clear_value_ ()
const ::std::string & value_ () const
void set_value_ (const ::std::string &value)
void set_value_ (const char *value)
void set_value_ (const char *value, size_t size)
::std::string * mutable_value_ ()
::std::string * release_value_ ()
void set_allocated_value_ (::std::string *value_)
Static Public Member Functions
static const Mode & default_instance ()
Static Public Attributes
static const int kTypeFieldNumber = 1
static const int kValueFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (Mode *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::internal::ArenaStringPtr type__
::google::protobuf::internal::ArenaStringPtr value__
int _cached_size_
Static Private Attributes
static Mode * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 1591 of file x3.pb.h.
Constructor & Destructor Documentation
x3::Mode::Mode ()
Definition at line 5381 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.Mode)
 }
x3::Mode::~Mode () virtual
Definition at line 5407 of file x3.pb.cc.
             {
   // @@protoc_insertion_point(destructor:x3.Mode)
   SharedDtor();
 }
x3::Mode::Mode (const Mode & from)
Definition at line 5391 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.Mode)
 }
Member Function Documentation
int x3::Mode::ByteSize () const
Definition at line 5543 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.Mode)
   int total_size = 0;
   // optional string type_ = 1;
   if (this->type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->type_());
   }
   // optional string value_ = 2;
   if (this->value_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->value_());
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::Mode::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 5567 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const Mode*>(&from));
 }
void x3::Mode::Clear ()
Definition at line 5447 of file x3.pb.cc.
Referenced by CopyFrom().
                  {
 // @@protoc_insertion_point(message_clear_start:x3.Mode)
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   value__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::Mode::clear_type_ () inline
Definition at line 6086 of file x3.pb.h.
{
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::Mode::clear_value_ () inline
Definition at line 6130 of file x3.pb.h.
{
   value__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::Mode::CopyFrom (const Mode & from)
Definition at line 5587 of file x3.pb.cc.
Referenced by operator=().
{
 // @@protoc_insertion_point(class_specific_copy_from_start:x3.Mode)
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
const Mode & x3::Mode::default_instance () static
Definition at line 5428 of file x3.pb.cc.
Referenced by SharedDtor().
{
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   protobuf_AddDesc_x3_2eproto();
 #else
   if (default_instance_ == NULL) protobuf_AddDesc_x3_2eproto();
 #endif
   return *default_instance_;
 }
void x3::Mode::DiscardUnknownFields ()
inline ::google::protobuf::Arena* x3::Mode::GetArenaNoVirtual () const inline private
Definition at line 1641 of file x3.pb.h.
{
     return _arena_ptr_;
   }
int x3::Mode::GetCachedSize () const inline
Definition at line 1634 of file x3.pb.h.
 { return _cached_size_; }
std::string x3::Mode::GetTypeName () const
Definition at line 5610 of file x3.pb.cc.
{
   return "x3.Mode";
 }
void x3::Mode::InitAsDefaultInstance () private
Definition at line 5387 of file x3.pb.cc.
Referenced by x3::protobuf_AddDesc_x3_2eproto().
{
   _is_default_instance_ = true;
 }
void x3::Mode::InternalSwap (Mode * other) private
Definition at line 5603 of file x3.pb.cc.
Referenced by Swap().
{
   type__.Swap(&other->type__);
   value__.Swap(&other->value__);
   _unknown_fields_.Swap(&other->_unknown_fields_);
   std::swap(_cached_size_, other->_cached_size_);
 }
bool x3::Mode::IsInitialized () const
Definition at line 5594 of file x3.pb.cc.
{
   return true;
 }
inline ::google::protobuf::Arena* x3::Mode::MaybeArenaPtr () const inline private
Definition at line 1644 of file x3.pb.h.
{
     return _arena_ptr_;