XProto Framework API Document: x3::CaptureTarget Class Reference
x3::CaptureTarget Class Reference
#include <x3.pb.h>
Public Member Functions
CaptureTarget ()
virtual ~CaptureTarget ()
CaptureTarget (const CaptureTarget &from)
CaptureTarget & operator= (const CaptureTarget &from)
void Swap (CaptureTarget *other)
CaptureTarget * New () const
CaptureTarget * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const CaptureTarget &from)
void MergeFrom (const CaptureTarget &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_type_ ()
const ::std::string & type_ () const
void set_type_ (const ::std::string &value)
void set_type_ (const char *value)
void set_type_ (const char *value, size_t size)
::std::string * mutable_type_ ()
::std::string * release_type_ ()
void set_allocated_type_ (::std::string *type_)
void clear_track_id_ ()
::google::protobuf::uint64 track_id_ () const
void set_track_id_ (::google::protobuf::uint64 value)
int captures__size () const
void clear_captures_ ()
const ::x3::Capture & captures_ (int index) const
::x3::Capture * mutable_captures_ (int index)
::x3::Capture * add_captures_ ()
::google::protobuf::RepeatedPtrField
< ::x3::Capture > * mutable_captures_ ()
const
::google::protobuf::RepeatedPtrField
< ::x3::Capture > & captures_ () const
int db_results__size () const
void clear_db_results_ ()
const ::x3::DBResult & db_results_ (int index) const
::x3::DBResult * mutable_db_results_ (int index)
::x3::DBResult * add_db_results_ ()
::google::protobuf::RepeatedPtrField
< ::x3::DBResult > * mutable_db_results_ ()
const
::google::protobuf::RepeatedPtrField
< ::x3::DBResult > & db_results_ () const
Static Public Member Functions
static const CaptureTarget & default_instance ()
Static Public Attributes
static const int kTypeFieldNumber = 1
static const int kTrackIdFieldNumber = 2
static const int kCapturesFieldNumber = 3
static const int kDbResultsFieldNumber = 4
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (CaptureTarget *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::internal::ArenaStringPtr type__
::google::protobuf::uint64 track_id__
::google::protobuf::RepeatedPtrField
< ::x3::Capture > captures__
::google::protobuf::RepeatedPtrField
< ::x3::DBResult > db_results__
int _cached_size_
Static Private Attributes
static CaptureTarget * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 2220 of file x3.pb.h.
Constructor & Destructor Documentation
x3::CaptureTarget::CaptureTarget ()
Definition at line 7696 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.CaptureTarget)
 }
x3::CaptureTarget::~CaptureTarget () virtual
Definition at line 7722 of file x3.pb.cc.
{
   // @@protoc_insertion_point(destructor:x3.CaptureTarget)
   SharedDtor();
 }
x3::CaptureTarget::CaptureTarget (const CaptureTarget & from)
Definition at line 7706 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.CaptureTarget)
 }
Member Function Documentation
x3::Capture * x3::CaptureTarget::add_captures_ () inline
Definition at line 6910 of file x3.pb.h.
Referenced by MergePartialFromCodedStream().
{
   // @@protoc_insertion_point(field_add:x3.CaptureTarget.captures_)
   return captures__.Add();
 }
x3::DBResult * x3::CaptureTarget::add_db_results_ () inline
Definition at line 6940 of file x3.pb.h.
Referenced by MergePartialFromCodedStream().
{
   // @@protoc_insertion_point(field_add:x3.CaptureTarget.db_results_)
   return db_results__.Add();
 }
int x3::CaptureTarget::ByteSize () const
Definition at line 7897 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.CaptureTarget)
   int total_size = 0;
   // optional string type_ = 1;
   if (this->type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->type_());
   }
   // optional uint64 track_id_ = 2;
   if (this->track_id_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::UInt64Size(
         this->track_id_());
   }
   // repeated .x3.Capture captures_ = 3;
   total_size += 1 * this->captures__size();
   for (int i = 0; i < this->captures__size(); i++) {
     total_size +=
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         this->captures_(i));
   }
   // repeated .x3.DBResult db_results_ = 4;
   total_size += 1 * this->db_results__size();
   for (int i = 0; i < this->db_results__size(); i++) {
     total_size +=
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         this->db_results_(i));
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
const ::x3::Capture & x3::CaptureTarget::captures_ (int index) const inline
Definition at line 6902 of file x3.pb.h.
{
   // @@protoc_insertion_point(field_get:x3.CaptureTarget.captures_)
   return captures__.Get(index);
 }
const ::google::protobuf::RepeatedPtrField<::x3::Capture > & x3::CaptureTarget::captures_ () const inline
Definition at line 6920 of file x3.pb.h.
Referenced by ByteSize(), and SerializeWithCachedSizes().
{
   // @@protoc_insertion_point(field_list:x3.CaptureTarget.captures_)
   return captures__;
 }
int x3::CaptureTarget::captures__size () const inline
Definition at line 6896 of file x3.pb.h.
Referenced by ByteSize(), and SerializeWithCachedSizes().
{
   return captures__.size();
 }
void x3::CaptureTarget::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 7937 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const CaptureTarget*>(&from));
 }
void x3::CaptureTarget::Clear ()
Definition at line 7761 of file x3.pb.cc.
Referenced by CopyFrom().
&