XProto Framework API Document: x3::ForwardMessage Class Reference
x3::ForwardMessage Class Reference
#include <x3.pb.h>
Public Member Functions
ForwardMessage ()
virtual ~ForwardMessage ()
ForwardMessage (const ForwardMessage &from)
ForwardMessage & operator= (const ForwardMessage &from)
void Swap (ForwardMessage *other)
ForwardMessage * New () const
ForwardMessage * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const ForwardMessage &from)
void MergeFrom (const ForwardMessage &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_source_session_id_ ()
::google::protobuf::uint32 source_session_id_ () const
void set_source_session_id_ (::google::protobuf::uint32 value)
void clear_version_ ()
const ::std::string & version_ () const
void set_version_ (const ::std::string &value)
void set_version_ (const char *value)
void set_version_ (const char *value, size_t size)
::std::string * mutable_version_ ()
::std::string * release_version_ ()
void set_allocated_version_ (::std::string *version_)
void clear_msg_type_ ()
const ::std::string & msg_type_ () const
void set_msg_type_ (const ::std::string &value)
void set_msg_type_ (const char *value)
void set_msg_type_ (const char *value, size_t size)
::std::string * mutable_msg_type_ ()
::std::string * release_msg_type_ ()
void set_allocated_msg_type_ (::std::string *msg_type_)
void clear_data_ ()
const ::std::string & data_ () const
void set_data_ (const ::std::string &value)
void set_data_ (const char *value)
void set_data_ (const void *value, size_t size)
::std::string * mutable_data_ ()
::std::string * release_data_ ()
void set_allocated_data_ (::std::string *data_)
Static Public Member Functions
static const ForwardMessage & default_instance ()
Static Public Attributes
static const int kSourceSessionIdFieldNumber = 1
static const int kVersionFieldNumber = 2
static const int kMsgTypeFieldNumber = 3
static const int kDataFieldNumber = 4
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (ForwardMessage *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::internal::ArenaStringPtr version__
::google::protobuf::internal::ArenaStringPtr msg_type__
::google::protobuf::internal::ArenaStringPtr data__
::google::protobuf::uint32 source_session_id__
int _cached_size_
Static Private Attributes
static ForwardMessage * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 2811 of file x3.pb.h.
Constructor & Destructor Documentation
x3::ForwardMessage::ForwardMessage ()
Definition at line 9622 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.ForwardMessage)
 }
x3::ForwardMessage::~ForwardMessage () virtual
Definition at line 9650 of file x3.pb.cc.
{
   // @@protoc_insertion_point(destructor:x3.ForwardMessage)
   SharedDtor();
 }
x3::ForwardMessage::ForwardMessage (const ForwardMessage & from)
Definition at line 9632 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.ForwardMessage)
 }
Member Function Documentation
int x3::ForwardMessage::ByteSize () const
Definition at line 9828 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.ForwardMessage)
   int total_size = 0;
   // optional uint32 source_session_id_ = 1;
   if (this->source_session_id_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::UInt32Size(
         this->source_session_id_());
   }
   // optional string version_ = 2;
   if (this->version_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->version_());
   }
   // optional string msg_type_ = 3;
   if (this->msg_type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->msg_type_());
   }
   // optional bytes data_ = 4;
   if (this->data_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::BytesSize(
         this->data_());
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::ForwardMessage::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 9866 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const ForwardMessage*>(&from));
 }
void x3::ForwardMessage::Clear ()
Definition at line 9691 of file x3.pb.cc.
Referenced by CopyFrom().
{
 // @@protoc_insertion_point(message_clear_start:x3.ForwardMessage)
   source_session_id__ = 0u;
   version__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   msg_type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   data__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::ForwardMessage::clear_data_ () inline
Definition at line 7478 of file x3.pb.h.
{
   data__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::ForwardMessage::clear_msg_type_ () inline
Definition at line 7434 of file x3.pb.h.
{
   msg_type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::ForwardMessage::clear_source_session_id_ () inline
Definition at line 7376 of file x3.pb.h.
{
   source_session_id__ = 0u;
 }
void x3::ForwardMessage::clear_version_ () inline
Definition at line 7390 of file x3.pb.h.
{
   version__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::ForwardMessage::CopyFrom (const ForwardMessage & from)
Definition at line 9893 of file x3.pb.cc.
Referenced by operator=().
{
 // @@protoc_insertion_point(class_specific_copy_from_start:x3.ForwardMessage)
   if (&from == this) return;