XProto Framework API Document: x3::Image Class Reference
x3::Image Class Reference
#include <x3.pb.h>
Public Member Functions
Image ()
virtual ~Image ()
Image (const Image &from)
Image & operator= (const Image &from)
void Swap (Image *other)
Image * New () const
Image * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const Image &from)
void MergeFrom (const Image &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_buf_ ()
const ::std::string & buf_ () const
void set_buf_ (const ::std::string &value)
void set_buf_ (const char *value)
void set_buf_ (const void *value, size_t size)
::std::string * mutable_buf_ ()
::std::string * release_buf_ ()
void set_allocated_buf_ (::std::string *buf_)
void clear_type_ ()
const ::std::string & type_ () const
void set_type_ (const ::std::string &value)
void set_type_ (const char *value)
void set_type_ (const char *value, size_t size)
::std::string * mutable_type_ ()
::std::string * release_type_ ()
void set_allocated_type_ (::std::string *type_)
void clear_width_ ()
::google::protobuf::uint32 width_ () const
void set_width_ (::google::protobuf::uint32 value)
void clear_height_ ()
::google::protobuf::uint32 height_ () const
void set_height_ (::google::protobuf::uint32 value)
Static Public Member Functions
static const Image & default_instance ()
Static Public Attributes
static const int kBufFieldNumber = 1
static const int kTypeFieldNumber = 2
static const int kWidthFieldNumber = 3
static const int kHeightFieldNumber = 4
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (Image *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::internal::ArenaStringPtr buf__
::google::protobuf::internal::ArenaStringPtr type__
::google::protobuf::uint32 width__
::google::protobuf::uint32 height__
int _cached_size_
Static Private Attributes
static Image * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 1260 of file x3.pb.h.
Constructor & Destructor Documentation
x3::Image::Image ()
Definition at line 4359 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.Image)
 }
x3::Image::~Image () virtual
Definition at line 4387 of file x3.pb.cc.
               {
   // @@protoc_insertion_point(destructor:x3.Image)
   SharedDtor();
 }
x3::Image::Image (const Image & from)
Definition at line 4369 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.Image)
 }
Member Function Documentation
const ::std::string & x3::Image::buf_ () const inline
Definition at line 5845 of file x3.pb.h.
Referenced by ByteSize(), MergeFrom(), and SerializeWithCachedSizes().
{
   // @@protoc_insertion_point(field_get:x3.Image.buf_)
   return buf__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
int x3::Image::ByteSize () const
Definition at line 4576 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.Image)
   int total_size = 0;
   // optional bytes buf_ = 1;
   if (this->buf_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::BytesSize(
         this->buf_());
   }
   // optional string type_ = 2;
   if (this->type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->type_());
   }
   // optional uint32 width_ = 3;
   if (this->width_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::UInt32Size(
         this->width_());
   }
   // optional uint32 height_ = 4;
   if (this->height_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::UInt32Size(
         this->height_());
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::Image::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 4614 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const Image*>(&from));
 }
void x3::Image::Clear ()
Definition at line 4427 of file x3.pb.cc.
Referenced by CopyFrom().
                   {
 // @@protoc_insertion_point(message_clear_start:x3.Image)
 #if defined(__clang__)
 #define ZR_HELPER_(f) \
   _Pragma("clang diagnostic push") \
   _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
   __builtin_offsetof(Image, f) \
   _Pragma("clang diagnostic pop")
 #else
 #define ZR_HELPER_(f) reinterpret_cast<char*>(\
   &reinterpret_cast<Image*>(16)->f)
 #endif
 #define ZR_(first, last) do {\
   ::memset(&first, 0,\
            ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
 } while (0)
   ZR_(width__, height__);
   buf__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 #undef ZR_HELPER_
 #undef ZR_
 }
void x3::Image::clear_buf_ () inline
Definition at line 5842 of file x3.pb.h.
{
   buf__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::Image::clear_height_ () inline
Definition at line 5944 of file x3.pb.h.
{
   height__ = 0u;
 }
void x3::Image::clear_type_ () inline
Definition at line 5886 of file x3.pb.h.
{
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::Image::clear_width_ () inline
Definition at line 5930 of file x3.pb.h.
{
   width__ = 0u;
 }
void x3::Image::CopyFrom (const Image & from)
Definition at line 4640 of file x3.pb.cc.
Referenced by operator=().
{