XProto Framework API Document: x3::Capture Class Reference
x3::Capture Class Reference
#include <x3.pb.h>
Public Member Functions
Capture ()
virtual ~Capture ()
Capture (const Capture &from)
Capture & operator= (const Capture &from)
void Swap (Capture *other)
Capture * New () const
Capture * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const Capture &from)
void MergeFrom (const Capture &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_type_ ()
const ::std::string & type_ () const
void set_type_ (const ::std::string &value)
void set_type_ (const char *value)
void set_type_ (const char *value, size_t size)
::std::string * mutable_type_ ()
::std::string * release_type_ ()
void set_allocated_type_ (::std::string *type_)
void clear_timestamp_ ()
::google::protobuf::uint64 timestamp_ () const
void set_timestamp_ (::google::protobuf::uint64 value)
bool has_img_ () const
void clear_img_ ()
const ::x3::Image & img_ () const
::x3::Image * mutable_img_ ()
::x3::Image * release_img_ ()
void set_allocated_img_ (::x3::Image *img_)
int boxes__size () const
void clear_boxes_ ()
const ::x3::Box & boxes_ (int index) const
::x3::Box * mutable_boxes_ (int index)
::x3::Box * add_boxes_ ()
::google::protobuf::RepeatedPtrField
< ::x3::Box > * mutable_boxes_ ()
const
::google::protobuf::RepeatedPtrField
< ::x3::Box > & boxes_ () const
int attributes__size () const
void clear_attributes_ ()
const ::x3::Attributes & attributes_ (int index) const
::x3::Attributes * mutable_attributes_ (int index)
::x3::Attributes * add_attributes_ ()
::google::protobuf::RepeatedPtrField
< ::x3::Attributes > * mutable_attributes_ ()
const
::google::protobuf::RepeatedPtrField
< ::x3::Attributes > & attributes_ () const
int points__size () const
void clear_points_ ()
const ::x3::Points & points_ (int index) const
::x3::Points * mutable_points_ (int index)
::x3::Points * add_points_ ()
::google::protobuf::RepeatedPtrField
< ::x3::Points > * mutable_points_ ()
const
::google::protobuf::RepeatedPtrField
< ::x3::Points > & points_ () const
int float_arrays__size () const
void clear_float_arrays_ ()
const ::x3::FloatArray & float_arrays_ (int index) const
::x3::FloatArray * mutable_float_arrays_ (int index)
::x3::FloatArray * add_float_arrays_ ()
::google::protobuf::RepeatedPtrField
< ::x3::FloatArray > * mutable_float_arrays_ ()
const
::google::protobuf::RepeatedPtrField
< ::x3::FloatArray > & float_arrays_ () const
int char_arrays__size () const
void clear_char_arrays_ ()
const ::x3::CharArray & char_arrays_ (int index) const
::x3::CharArray * mutable_char_arrays_ (int index)
::x3::CharArray * add_char_arrays_ ()
::google::protobuf::RepeatedPtrField
< ::x3::CharArray > * mutable_char_arrays_ ()
const
::google::protobuf::RepeatedPtrField
< ::x3::CharArray > & char_arrays_ () const
Static Public Member Functions
static const Capture & default_instance ()
Static Public Attributes
static const int kTypeFieldNumber = 1
static const int kTimestampFieldNumber = 2
static const int kImgFieldNumber = 3
static const int kBoxesFieldNumber = 4
static const int kAttributesFieldNumber = 5
static const int kPointsFieldNumber = 6
static const int kFloatArraysFieldNumber = 7
static const int kCharArraysFieldNumber = 8
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (Capture *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::internal::ArenaStringPtr type__
::google::protobuf::uint64 timestamp__
::x3::Image * img__
::google::protobuf::RepeatedPtrField
< ::x3::Box > boxes__
::google::protobuf::RepeatedPtrField
< ::x3::Attributes > attributes__
::google::protobuf::RepeatedPtrField
< ::x3::Points > points__
::google::protobuf::RepeatedPtrField
< ::x3::FloatArray > float_arrays__
::google::protobuf::RepeatedPtrField
< ::x3::CharArray > char_arrays__
int _cached_size_
Static Private Attributes
static Capture * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 2041 of file x3.pb.h.
Constructor & Destructor Documentation
x3::Capture::Capture ()
Definition at line 7004 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.Capture)
 }
x3::Capture::~Capture () virtual
Definition at line 7037 of file x3.pb.cc.
                   {
   // @@protoc_insertion_point(destructor:x3.Capture)
   SharedDtor();
 }
x3::Capture::Capture (const Capture & from)
Definition at line 7020 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.Capture)
 }
Member Function Documentation
x3::Attributes * x3::Capture::add_attributes_ () inline
Definition at line 6728 of file x3.pb.h.
Referenced by MergePartialFromCodedStream().
{
   // @@protoc_insertion_point(field_add:x3.Capture.attributes_)
   return attributes__.Add();
 }
x3::Box * x3::Capture::add_boxes_ () inline
Definition at line 6698 of file x3.pb.h.
Referenced by MergePartialFromCodedStream().
{
   // @@protoc_insertion_point(field_add:x3.Capture.boxes_)
   return boxes__.Add();
 }
x3::CharArray * x3::Capture::add_char_arrays_ () inline
Definition at line 6818 of file x3.pb.h.
Referenced by MergePartialFromCodedStream().
{
   // @@protoc_insertion_point(field_add:x3.Capture.char_arrays_)
   return char_arrays__.Add();
 }
x3::FloatArray * x3::Capture::add_float_arrays_ () inline
Definition at line 6788 of file x3.pb.h<