XProto Framework API Document: x3::CharArray Class Reference
x3::CharArray Class Reference
#include <x3.pb.h>
Public Member Functions
CharArray ()
virtual ~CharArray ()
CharArray (const CharArray &from)
CharArray & operator= (const CharArray &from)
void Swap (CharArray *other)
CharArray * New () const
CharArray * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const CharArray &from)
void MergeFrom (const CharArray &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_type_ ()
const ::std::string & type_ () const
void set_type_ (const ::std::string &value)
void set_type_ (const char *value)
void set_type_ (const char *value, size_t size)
::std::string * mutable_type_ ()
::std::string * release_type_ ()
void set_allocated_type_ (::std::string *type_)
void clear_score_ ()
float score_ () const
void set_score_ (float value)
void clear_array_ ()
const ::std::string & array_ () const
void set_array_ (const ::std::string &value)
void set_array_ (const char *value)
void set_array_ (const void *value, size_t size)
::std::string * mutable_array_ ()
::std::string * release_array_ ()
void set_allocated_array_ (::std::string *array_)
void clear_name_ ()
const ::std::string & name_ () const
void set_name_ (const ::std::string &value)
void set_name_ (const char *value)
void set_name_ (const char *value, size_t size)
::std::string * mutable_name_ ()
::std::string * release_name_ ()
void set_allocated_name_ (::std::string *name_)
void clear_specific_type_ ()
const ::std::string & specific_type_ () const
void set_specific_type_ (const ::std::string &value)
void set_specific_type_ (const char *value)
void set_specific_type_ (const char *value, size_t size)
::std::string * mutable_specific_type_ ()
::std::string * release_specific_type_ ()
void set_allocated_specific_type_ (::std::string *specific_type_)
Static Public Member Functions
static const CharArray & default_instance ()
Static Public Attributes
static const int kTypeFieldNumber = 1
static const int kScoreFieldNumber = 2
static const int kArrayFieldNumber = 3
static const int kNameFieldNumber = 4
static const int kSpecificTypeFieldNumber = 5
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (CharArray *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::internal::ArenaStringPtr type__
::google::protobuf::internal::ArenaStringPtr array__
::google::protobuf::internal::ArenaStringPtr name__
::google::protobuf::internal::ArenaStringPtr specific_type__
float score__
int _cached_size_
Static Private Attributes
static CharArray * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 167 of file x3.pb.h.
Constructor & Destructor Documentation
x3::CharArray::CharArray ()
Definition at line 162 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.CharArray)
 }
x3::CharArray::~CharArray () virtual
Definition at line 191 of file x3.pb.cc.
                       {
   // @@protoc_insertion_point(destructor:x3.CharArray)
   SharedDtor();
 }
x3::CharArray::CharArray (const CharArray & from)
Definition at line 172 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.CharArray)
 }
Member Function Documentation
const ::std::string & x3::CharArray::array_ () const inline
Definition at line 4531 of file x3.pb.h.
Referenced by ByteSize(), MergeFrom(), and SerializeWithCachedSizes().
{
   // @@protoc_insertion_point(field_get:x3.CharArray.array_)
   return array__.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
int x3::CharArray::ByteSize () const
Definition at line 398 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.CharArray)
   int total_size = 0;
   // optional string type_ = 1;
   if (this->type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->type_());
   }
   // optional float score_ = 2;
   if (this->score_() != 0) {
     total_size += 1 + 4;
   }
   // optional bytes array_ = 3;
   if (this->array_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::BytesSize(
         this->array_());
   }
   // optional string name_ = 4;
   if (this->name_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->name_());
   }
   // optional string specific_type_ = 5;
   if (this->specific_type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->specific_type_());
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::CharArray::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 441 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const CharArray*>(&from));
 }
void x3::CharArray::Clear ()
Definition at line 233 of file x3.pb.cc.
Referenced by CopyFrom().
                       {
 // @@protoc_insertion_point(message_clear_start:x3.CharArray)
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   score__ = 0;
   array__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   name__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   specific_type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::CharArray::clear_array_ () inline
Definition at line 4528 of file x3.pb.h.
{
   array__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }