XProto Framework API Document: x3::Command Class Reference
x3::Command Class Reference
#include <x3.pb.h>
Public Types
typedef Command_Order Order
Public Member Functions
Command ()
virtual ~Command ()
Command (const Command &from)
Command & operator= (const Command &from)
void Swap (Command *other)
Command * New () const
Command * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const Command &from)
void MergeFrom (const Command &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_type_ ()
const ::std::string & type_ () const
void set_type_ (const ::std::string &value)
void set_type_ (const char *value)
void set_type_ (const char *value, size_t size)
::std::string * mutable_type_ ()
::std::string * release_type_ ()
void set_allocated_type_ (::std::string *type_)
void clear_timestamp_ ()
::google::protobuf::uint64 timestamp_ () const
void set_timestamp_ (::google::protobuf::uint64 value)
void clear_order_ ()
::x3::Command_Order order_ () const
void set_order_ (::x3::Command_Order value)
Static Public Member Functions
static const Command & default_instance ()
static bool Order_IsValid (int value)
Static Public Attributes
static const Order Unkown
static const Order StartX2
static const Order StopX2
static const Order UpdateX2
static const Order Order_MIN
static const Order Order_MAX
static const int Order_ARRAYSIZE
static const int kTypeFieldNumber = 1
static const int kTimestampFieldNumber = 2
static const int kOrderFieldNumber = 3
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (Command *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::internal::ArenaStringPtr type__
::google::protobuf::uint64 timestamp__
int order__
int _cached_size_
Static Private Attributes
static Command * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 3425 of file x3.pb.h.
Member Typedef Documentation
typedef Command_Order x3::Command::Order
Definition at line 3487 of file x3.pb.h.
Constructor & Destructor Documentation
x3::Command::Command ()
Definition at line 11590 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.Command)
 }
x3::Command::~Command () virtual
Definition at line 11617 of file x3.pb.cc.
                   {
   // @@protoc_insertion_point(destructor:x3.Command)
   SharedDtor();
 }
x3::Command::Command (const Command & from)
Definition at line 11600 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.Command)
 }
Member Function Documentation
int x3::Command::ByteSize () const
Definition at line 11787 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.Command)
   int total_size = 0;
   // optional string type_ = 1;
   if (this->type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->type_());
   }
   // optional uint64 timestamp_ = 2;
   if (this->timestamp_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::UInt64Size(
         this->timestamp_());
   }
   // optional .x3.Command.Order order_ = 3;
   if (this->order_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::EnumSize(this->order_());
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::Command::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 11817 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const Command*>(&from));
 }
void x3::Command::Clear ()
Definition at line 11656 of file x3.pb.cc.
Referenced by CopyFrom().
                     {
 // @@protoc_insertion_point(message_clear_start:x3.Command)
 #if defined(__clang__)
 #define ZR_HELPER_(f) \
   _Pragma("clang diagnostic push") \
   _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
   __builtin_offsetof(Command, f) \
   _Pragma("clang diagnostic pop")
 #else
 #define ZR_HELPER_(f) reinterpret_cast<char*>(\
   &reinterpret_cast<Command*>(16)->f)
 #endif
 #define ZR_(first, last) do {\
   ::memset(&first, 0,\
            ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
 } while (0)
   ZR_(timestamp__, order__);
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 #undef ZR_HELPER_
 #undef ZR_
 }
void x3::Command::clear_order_ () inline
Definition at line 7980 of file x3.pb.h.
{
   order__ = 0;
 }
void x3::Command::clear_timestamp_ () inline
Definition at line 7966 of file x3.pb.h.
{
   timestamp__ = GOOGLE_ULONGLONG(0);
 }
void x3::Command::clear_type_ () inline
Definition at line 7922 of file x3.pb.h.
{
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::Command::CopyFrom (const Command & from)
Definition at line 11839 of file x3.pb.cc.
Referenced by operator=().
{
 // @@protoc_insertion_point(class_specific_copy_from_start:x3.Command)
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
const Command & x3::Command::default_instance () static
Definition at line 11637 of file x3.pb.cc.
Referenced by x3::InfoMessage::InitAsDefaultInstance(), and SharedDtor().
{
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   protobuf_AddDesc_x3_2eproto();
 #else
   if (default_instance_ == NULL) protobuf_AddDesc_x3_2eproto();
 #endif
   return *default_instance_;
 }