XProto Framework API Document: x3::Version Class Reference
x3::Version Class Reference
#include <x3.pb.h>
Public Member Functions
Version ()
virtual ~Version ()
Version (const Version &from)
Version & operator= (const Version &from)
void Swap (Version *other)
Version * New () const
Version * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const Version &from)
void MergeFrom (const Version &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_type_ ()
const ::std::string & type_ () const
void set_type_ (const ::std::string &value)
void set_type_ (const char *value)
void set_type_ (const char *value, size_t size)
::std::string * mutable_type_ ()
::std::string * release_type_ ()
void set_allocated_type_ (::std::string *type_)
void clear_value_ ()
const ::std::string & value_ () const
void set_value_ (const ::std::string &value)
void set_value_ (const char *value)
void set_value_ (const char *value, size_t size)
::std::string * mutable_value_ ()
::std::string * release_value_ ()
void set_allocated_value_ (::std::string *value_)
Static Public Member Functions
static const Version & default_instance ()
Static Public Attributes
static const int kTypeFieldNumber = 1
static const int kValueFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (Version *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::internal::ArenaStringPtr type__
::google::protobuf::internal::ArenaStringPtr value__
int _cached_size_
Static Private Attributes
static Version * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 3046 of file x3.pb.h.
Constructor & Destructor Documentation
x3::Version::Version ()
Definition at line 10409 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.Version)
 }
x3::Version::~Version () virtual
Definition at line 10435 of file x3.pb.cc.
                   {
   // @@protoc_insertion_point(destructor:x3.Version)
   SharedDtor();
 }
x3::Version::Version (const Version & from)
Definition at line 10419 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.Version)
 }
Member Function Documentation
int x3::Version::ByteSize () const
Definition at line 10571 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.Version)
   int total_size = 0;
   // optional string type_ = 1;
   if (this->type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->type_());
   }
   // optional string value_ = 2;
   if (this->value_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->value_());
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::Version::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 10595 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const Version*>(&from));
 }
void x3::Version::Clear ()
Definition at line 10475 of file x3.pb.cc.
Referenced by CopyFrom().
                     {
 // @@protoc_insertion_point(message_clear_start:x3.Version)
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   value__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::Version::clear_type_ () inline
Definition at line 7616 of file x3.pb.h.
{
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::Version::clear_value_ () inline
Definition at line 7660 of file x3.pb.h.
{
   value__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::Version::CopyFrom (const Version & from)
Definition at line 10615 of file x3.pb.cc.
Referenced by operator=().
{
 // @@protoc_insertion_point(class_specific_copy_from_start:x3.Version)
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
const Version & x3::Version::default_instance () static
Definition at line 10456 of file x3.pb.cc.
Referenced by SharedDtor().
{
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   protobuf_AddDesc_x3_2eproto();
 #else
   if (default_instance_ == NULL) protobuf_AddDesc_x3_2eproto();
 #endif
   return *default_instance_;
 }
void x3::Version::DiscardUnknownFields ()
inline ::google::protobuf::Arena* x3::Version::GetArenaNoVirtual () const inline private
Definition at line 3096 of file x3.pb.h.
{
     return _arena_ptr_;
   }
int x3::Version::GetCachedSize () const inline
Definition at line 3089 of file x3.pb.h.
 { return _cached_size_; }
std::string x3::Version::GetTypeName () const
Definition at line 10638 of file x3.pb.cc.
{
   return "x3.Version";
 }
void x3::Version::InitAsDefaultInstance () private
Definition at line 10415 of file x3.pb.cc.
Referenced by x3::protobuf_AddDesc_x3_2eproto().
{
   _is_default_instance_ = true;
 }
void x3::Version::InternalSwap (Version * other) private
Definition at line 10631 of file x3.pb.cc.
Referenced by Swap().
{
   type__.Swap(&other->type__);
   value__.Swap(&other->value__);
   _unknown_fields_.Swap(&other->_unknown_fields_);
   std::swap(_cached_size_, other->_cached_size_);
 }
bool x3::Version::IsInitialized () const
Definition at line 10622 of file x3.pb.cc.
{
   return true;
 }
inline ::google::protobuf::Arena* x3::Version::MaybeArenaPtr () c