XProto Framework API Document: x3::Box Class Reference
x3::Box Class Reference
#include <x3.pb.h>
Public Member Functions
Box ()
virtual ~Box ()
Box (const Box &from)
Box & operator= (const Box &from)
void Swap (Box *other)
Box * New () const
Box * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const Box &from)
void MergeFrom (const Box &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_type_ ()
const ::std::string & type_ () const
void set_type_ (const ::std::string &value)
void set_type_ (const char *value)
void set_type_ (const char *value, size_t size)
::std::string * mutable_type_ ()
::std::string * release_type_ ()
void set_allocated_type_ (::std::string *type_)
bool has_top_left_ () const
void clear_top_left_ ()
const ::x3::Point & top_left_ () const
::x3::Point * mutable_top_left_ ()
::x3::Point * release_top_left_ ()
void set_allocated_top_left_ (::x3::Point *top_left_)
bool has_bottom_right_ () const
void clear_bottom_right_ ()
const ::x3::Point & bottom_right_ () const
::x3::Point * mutable_bottom_right_ ()
::x3::Point * release_bottom_right_ ()
void set_allocated_bottom_right_ (::x3::Point *bottom_right_)
void clear_score_ ()
float score_ () const
void set_score_ (float value)
void clear_name_ ()
const ::std::string & name_ () const
void set_name_ (const ::std::string &value)
void set_name_ (const char *value)
void set_name_ (const char *value, size_t size)
::std::string * mutable_name_ ()
::std::string * release_name_ ()
void set_allocated_name_ (::std::string *name_)
void clear_specific_type_ ()
const ::std::string & specific_type_ () const
void set_specific_type_ (const ::std::string &value)
void set_specific_type_ (const char *value)
void set_specific_type_ (const char *value, size_t size)
::std::string * mutable_specific_type_ ()
::std::string * release_specific_type_ ()
void set_allocated_specific_type_ (::std::string *specific_type_)
Static Public Member Functions
static const Box & default_instance ()
Static Public Attributes
static const int kTypeFieldNumber = 1
static const int kTopLeftFieldNumber = 2
static const int kBottomRightFieldNumber = 3
static const int kScoreFieldNumber = 4
static const int kNameFieldNumber = 5
static const int kSpecificTypeFieldNumber = 6
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (Box *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::internal::ArenaStringPtr type__
::x3::Point * top_left__
::x3::Point * bottom_right__
::google::protobuf::internal::ArenaStringPtr name__
::google::protobuf::internal::ArenaStringPtr specific_type__
float score__
int _cached_size_
Static Private Attributes
static Box * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 830 of file x3.pb.h.
Constructor & Destructor Documentation
x3::Box::Box ()
Definition at line 2580 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.Box)
 }
x3::Box::~Box () virtual
Definition at line 2622 of file x3.pb.cc.
           {
   // @@protoc_insertion_point(destructor:x3.Box)
   SharedDtor();
 }
x3::Box::Box (const Box & from)
Definition at line 2602 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.Box)
 }
Member Function Documentation
const ::x3::Point & x3::Box::bottom_right_ () const inline
Definition at line 5329 of file x3.pb.h.
Referenced by MergeFrom(), and set_allocated_bottom_right_().
{
   // @@protoc_insertion_point(field_get:x3.Box.bottom_right_)
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   return bottom_right__ != NULL ? *bottom_right__ : *default_instance().bottom_right__;
 #else
   return bottom_right__ != NULL ? *bottom_right__ : *default_instance_->bottom_right__;
 #endif
 }
int x3::Box::ByteSize () const
Definition at line 2852 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.Box)
   int total_size = 0;
   // optional string type_ = 1;
   if (this->type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->type_());
   }
   // optional .x3.Point top_left_ = 2;
   if (this->has_top_left_()) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         *this->top_left__);
   }
   // optional .x3.Point bottom_right_ = 3;
   if (this->has_bottom_right_()) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         *this->bottom_right__);
   }
   // optional float score_ = 4;
   if (this->score_() != 0) {
     total_size += 1 + 4;
   }
   // optional string name_ = 5;
   if (this->name_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->name_());
   }
   // optional string specific_type_ = 6;
   if (this->specific_type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->specific_type_());
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::Box::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 2902 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const Box*>(&from));
 }