XProto Framework API Document: x3::FloatMatrix Class Reference
x3::FloatMatrix Class Reference
#include <x3.pb.h>
Public Member Functions
FloatMatrix ()
virtual ~FloatMatrix ()
FloatMatrix (const FloatMatrix &from)
FloatMatrix & operator= (const FloatMatrix &from)
void Swap (FloatMatrix *other)
FloatMatrix * New () const
FloatMatrix * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const FloatMatrix &from)
void MergeFrom (const FloatMatrix &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_type_ ()
const ::std::string & type_ () const
void set_type_ (const ::std::string &value)
void set_type_ (const char *value)
void set_type_ (const char *value, size_t size)
::std::string * mutable_type_ ()
::std::string * release_type_ ()
void set_allocated_type_ (::std::string *type_)
void clear_score_ ()
float score_ () const
void set_score_ (float value)
int arrays__size () const
void clear_arrays_ ()
const ::x3::FloatArray & arrays_ (int index) const
::x3::FloatArray * mutable_arrays_ (int index)
::x3::FloatArray * add_arrays_ ()
::google::protobuf::RepeatedPtrField
< ::x3::FloatArray > * mutable_arrays_ ()
const
::google::protobuf::RepeatedPtrField
< ::x3::FloatArray > & arrays_ () const
void clear_name_ ()
const ::std::string & name_ () const
void set_name_ (const ::std::string &value)
void set_name_ (const char *value)
void set_name_ (const char *value, size_t size)
::std::string * mutable_name_ ()
::std::string * release_name_ ()
void set_allocated_name_ (::std::string *name_)
void clear_specific_type_ ()
const ::std::string & specific_type_ () const
void set_specific_type_ (const ::std::string &value)
void set_specific_type_ (const char *value)
void set_specific_type_ (const char *value, size_t size)
::std::string * mutable_specific_type_ ()
::std::string * release_specific_type_ ()
void set_allocated_specific_type_ (::std::string *specific_type_)
Static Public Member Functions
static const FloatMatrix & default_instance ()
Static Public Attributes
static const int kTypeFieldNumber = 1
static const int kScoreFieldNumber = 2
static const int kArraysFieldNumber = 3
static const int kNameFieldNumber = 4
static const int kSpecificTypeFieldNumber = 5
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (FloatMatrix *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::internal::ArenaStringPtr type__
::google::protobuf::RepeatedPtrField
< ::x3::FloatArray > arrays__
::google::protobuf::internal::ArenaStringPtr name__
::google::protobuf::internal::ArenaStringPtr specific_type__
float score__
int _cached_size_
Static Private Attributes
static FloatMatrix * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 449 of file x3.pb.h.
Constructor & Destructor Documentation
x3::FloatMatrix::FloatMatrix ()
Definition at line 1249 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.FloatMatrix)
 }
x3::FloatMatrix::~FloatMatrix () virtual
Definition at line 1277 of file x3.pb.cc.
{
   // @@protoc_insertion_point(destructor:x3.FloatMatrix)
   SharedDtor();
 }
x3::FloatMatrix::FloatMatrix (const FloatMatrix & from)
Definition at line 1259 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.FloatMatrix)
 }
Member Function Documentation
x3::FloatArray * x3::FloatMatrix::add_arrays_ () inline
Definition at line 4916 of file x3.pb.h.
Referenced by MergePartialFromCodedStream().
{
   // @@protoc_insertion_point(field_add:x3.FloatMatrix.arrays_)
   return arrays__.Add();
 }
const ::x3::FloatArray & x3::FloatMatrix::arrays_ (int index) const inline
Definition at line 4908 of file x3.pb.h.
{
   // @@protoc_insertion_point(field_get:x3.FloatMatrix.arrays_)
   return arrays__.Get(index);
 }
const ::google::protobuf::RepeatedPtrField<::x3::FloatArray > & x3::FloatMatrix::arrays_ () const inline
Definition at line 4926 of file x3.pb.h.
Referenced by ByteSize(), and SerializeWithCachedSizes().
{
   // @@protoc_insertion_point(field_list:x3.FloatMatrix.arrays_)
   return arrays__;
 }
int x3::FloatMatrix::arrays__size () const inline
Definition at line 4902 of file x3.pb.h.
Referenced by ByteSize(), and SerializeWithCachedSizes().
{
   return arrays__.size();
 }
int x3::FloatMatrix::ByteSize () const
Definition at line 1487 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.FloatMatrix)
   int total_size = 0;
   // optional string type_ = 1;
   if (this->type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->type_());
   }
   // optional float score_ = 2;
   if (this->score_() != 0) {
     total_size += 1 + 4;
   }
   // optional string name_ = 4;
   if (this->name_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->name_());
   }
   // optional string specific_type_ = 5;
   if (this->specific_type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->specific_type_());
   }
   // repeated .x3.FloatArray arrays_ = 3;
   total_size += 1 * this->arrays__size();
   for (int i = 0; i < this->arrays__size(); i++) {
     total_size +=
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         this->arrays_(i));
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::FloatMatrix::CheckTypeAndMergeFrom (