XProto Framework API Document: x3::SmartLegibleMessage Class Reference
x3::SmartLegibleMessage Class Reference
#include <x3.pb.h>
Public Member Functions
SmartLegibleMessage ()
virtual ~SmartLegibleMessage ()
SmartLegibleMessage (const SmartLegibleMessage &from)
SmartLegibleMessage & operator= (const SmartLegibleMessage &from)
void Swap (SmartLegibleMessage *other)
SmartLegibleMessage * New () const
SmartLegibleMessage * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const SmartLegibleMessage &from)
void MergeFrom (const SmartLegibleMessage &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_timestamp_ ()
::google::protobuf::uint64 timestamp_ () const
void set_timestamp_ (::google::protobuf::uint64 value)
void clear_error_code_ ()
::google::protobuf::uint32 error_code_ () const
void set_error_code_ (::google::protobuf::uint32 value)
void clear_sequence_id_ ()
::google::protobuf::uint64 sequence_id_ () const
void set_sequence_id_ (::google::protobuf::uint64 value)
void clear_channel_id_ ()
::google::protobuf::uint32 channel_id_ () const
void set_channel_id_ (::google::protobuf::uint32 value)
void clear_frame_id_ ()
::google::protobuf::uint64 frame_id_ () const
void set_frame_id_ (::google::protobuf::uint64 value)
int targets__size () const
void clear_targets_ ()
const ::x3::Target & targets_ (int index) const
::x3::Target * mutable_targets_ (int index)
::x3::Target * add_targets_ ()
::google::protobuf::RepeatedPtrField
< ::x3::Target > * mutable_targets_ ()
const
::google::protobuf::RepeatedPtrField
< ::x3::Target > & targets_ () const
Static Public Member Functions
static const SmartLegibleMessage & default_instance ()
Static Public Attributes
static const int kTimestampFieldNumber = 1
static const int kErrorCodeFieldNumber = 2
static const int kSequenceIdFieldNumber = 3
static const int kChannelIdFieldNumber = 4
static const int kFrameIdFieldNumber = 5
static const int kTargetsFieldNumber = 6
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (SmartLegibleMessage *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::uint64 timestamp__
::google::protobuf::uint64 sequence_id__
::google::protobuf::uint32 error_code__
::google::protobuf::uint32 channel_id__
::google::protobuf::uint64 frame_id__
::google::protobuf::RepeatedPtrField
< ::x3::Target > targets__
int _cached_size_
Static Private Attributes
static SmartLegibleMessage * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 1908 of file x3.pb.h.
Constructor & Destructor Documentation
x3::SmartLegibleMessage::SmartLegibleMessage ()
Definition at line 6525 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.SmartLegibleMessage)
 }
x3::SmartLegibleMessage::~SmartLegibleMessage () virtual
Definition at line 6553 of file x3.pb.cc.
{
   // @@protoc_insertion_point(destructor:x3.SmartLegibleMessage)
   SharedDtor();
 }
x3::SmartLegibleMessage::SmartLegibleMessage (const SmartLegibleMessage & from)
Definition at line 6535 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.SmartLegibleMessage)
 }
Member Function Documentation
x3::Target * x3::SmartLegibleMessage::add_targets_ () inline
Definition at line 6564 of file x3.pb.h.
Referenced by MergePartialFromCodedStream().
{
   // @@protoc_insertion_point(field_add:x3.SmartLegibleMessage.targets_)
   return targets__.Add();
 }
int x3::SmartLegibleMessage::ByteSize () const
Definition at line 6776 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.SmartLegibleMessage)
   int total_size = 0;
   // optional fixed64 timestamp_ = 1;
   if (this->timestamp_() != 0) {
     total_size += 1 + 8;
   }
   // optional uint32 error_code_ = 2;
   if (this->error_code_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::UInt32Size(
         this->error_code_());
   }
   // optional uint64 sequence_id_ = 3;
   if (this->sequence_id_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::UInt64Size(
         this->sequence_id_());
   }
   // optional uint32 channel_id_ = 4;
   if (this->channel_id_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::UInt32Size(
         this->channel_id_());
   }
   // optional uint64 frame_id_ = 5;
   if (this->frame_id_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::UInt64Size(
         this->frame_id_());
   }
   // repeated .x3.Target targets_ = 6;
   total_size += 1 * this->targets__size();
   for (int i = 0; i < this->targets__size(); i++) {
     total_size +=
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         this->targets_(i));
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
google::protobuf::uint32 x3::SmartLegibleMessage::channel_id_ () const inline
Definition at line 6525 of file x3.pb.h.
Referenced by ByteSize(), MergeFrom(), and SerializeWithCachedSizes().
{
   // @@protoc_insertion_point(field_get:x3.SmartLegibleMessage.channel_id_)
   return channel_id__;
 }
void x3::SmartLegibleMessage::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 6827 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const SmartLegibleMessage*>(&from));
 }
void x3::SmartLegibleMessage::Clear ()
Definition at line 6591 of file x3.pb.cc.
Referenced by CopyFrom().
{
 // @@protoc_insertion_point(message_clear_start:x3.SmartLegibleMessage)
 #if defined(__clang__)
 #define ZR_HELPER_(f) \
   _Pragma("clang diagnostic push") \
   _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
   __builtin_offsetof(SmartLegibleMessage, f) \
   _Pragma("clang diagnostic pop")
 #else
 #define ZR_HELPER_(f) reinterpret_cast<char*>(\
   &reinterpret_cast<SmartLegibleMessage*>(16)->f)
 #endif
 #define ZR_(first, last) do {\
   ::memset(&first, 0,\
            ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
 } while (0)