XProto Framework API Document: x3::Check Class Reference
x3::Check Class Reference
#include <x3.pb.h>
Public Member Functions
Check ()
virtual ~Check ()
Check (const Check &from)
Check & operator= (const Check &from)
void Swap (Check *other)
Check * New () const
Check * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const Check &from)
void MergeFrom (const Check &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
int md5sum_size () const
void clear_md5sum ()
const ::std::string & md5sum (int index) const
::std::string * mutable_md5sum (int index)
void set_md5sum (int index, const ::std::string &value)
void set_md5sum (int index, const char *value)
void set_md5sum (int index, const void *value, size_t size)
::std::string * add_md5sum ()
void add_md5sum (const ::std::string &value)
void add_md5sum (const char *value)
void add_md5sum (const void *value, size_t size)
const
::google::protobuf::RepeatedPtrField
< ::std::string > & md5sum () const
::google::protobuf::RepeatedPtrField
< ::std::string > * mutable_md5sum ()
Static Public Member Functions
static const Check & default_instance ()
Static Public Attributes
static const int kMd5SumFieldNumber = 1
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (Check *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::RepeatedPtrField
< ::std::string > md5sum_
int _cached_size_
Static Private Attributes
static Check * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 4101 of file x3.pb.h.
Constructor & Destructor Documentation
x3::Check::Check ()
Definition at line 13678 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.Check)
 }
x3::Check::~Check () virtual
Definition at line 13702 of file x3.pb.cc.
               {
   // @@protoc_insertion_point(destructor:x3.Check)
   SharedDtor();
 }
x3::Check::Check (const Check & from)
Definition at line 13688 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.Check)
 }
Member Function Documentation
std::string * x3::Check::add_md5sum () inline
Definition at line 8471 of file x3.pb.h.
Referenced by MergePartialFromCodedStream().
{
   // @@protoc_insertion_point(field_add_mutable:x3.Check.md5sum)
   return md5sum_.Add();
 }
void x3::Check::add_md5sum (const ::std::string & value) inline
Definition at line 8475 of file x3.pb.h.
{
   md5sum_.Add()->assign(value);
   // @@protoc_insertion_point(field_add:x3.Check.md5sum)
 }
void x3::Check::add_md5sum (const char * value) inline
Definition at line 8479 of file x3.pb.h.
{
   md5sum_.Add()->assign(value);
   // @@protoc_insertion_point(field_add_char:x3.Check.md5sum)
 }
void x3::Check::add_md5sum (const void * value, size_t size) inline
Definition at line 8483 of file x3.pb.h.
{
   md5sum_.Add()->assign(reinterpret_cast<const char*>(value), size);
   // @@protoc_insertion_point(field_add_pointer:x3.Check.md5sum)
 }
int x3::Check::ByteSize () const
Definition at line 13802 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.Check)
   int total_size = 0;
   // repeated bytes md5sum = 1;
   total_size += 1 * this->md5sum_size();
   for (int i = 0; i < this->md5sum_size(); i++) {
     total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
       this->md5sum(i));
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::Check::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 13819 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const Check*>(&from));
 }
void x3::Check::Clear ()
Definition at line 13740 of file x3.pb.cc.
Referenced by CopyFrom().
                   {
 // @@protoc_insertion_point(message_clear_start:x3.Check)
   md5sum_.Clear();
 }
void x3::Check::clear_md5sum () inline
Definition at line 8447 of file x3.pb.h.
{
   md5sum_.Clear();
 }
void x3::Check::CopyFrom (const Check & from)
Definition at line 13832 of file x3.pb.cc.
Referenced by operator=().
{
 // @@protoc_insertion_point(class_specific_copy_from_start:x3.Check)
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
const Check & x3::Check::default_instance () static
Definition at line 13721 of file x3.pb.cc.
Referenced by x3::Addition::InitAsDefaultInstance(), and SharedDtor().
{
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   protobuf_AddDesc_x3_2eproto();
 #else
   if (default_instance_ == NULL) protobuf_AddDesc_x3_2eproto();
 #endif
   return *default_instance_;
 }
void x3::Check::DiscardUnknownFields ()
inline ::google::protobuf::Arena* x3::Check::GetArenaNoVirtual () const inline private
Definition at line 4151 of file x3.pb.h.
{
     return _arena_ptr_;
   }
int x3::Check::GetCachedSize () const inline
Definition at line 4144 of file x3.pb.h.
 { return _cached_size_; }
std::string x3::Check::GetTypeName () const
Definition at line 13854 of file x3.pb.cc.
{
   return "x3.Check";
 }
void x3::Check::InitAsDefaultInstance () private
Definition at line 13684 of file x3.pb.cc.
Referenced by x3::protobuf_AddDesc_x3_2eproto().
{
   _is_default_instance_ = true;
 }
void x3::Check::InternalSwap (Check * other) private
Definition at line 13848 of file x3.pb.cc.
Referenced by Swap().
{
   md5sum_.UnsafeArenaSwap(&other->md5sum_);
   _unknown_fields_.Swap(&other->_unknown_fields_);
   std::swap(_cached_size_, other->_cached_size_);
 }