XProto Framework API Document: x3::Status Class Reference
x3::Status Class Reference
#include <x3.pb.h>
Public Types
typedef Status_RunStatus RunStatus
Public Member Functions
Status ()
virtual ~Status ()
Status (const Status &from)
Status & operator= (const Status &from)
void Swap (Status *other)
Status * New () const
Status * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const Status &from)
void MergeFrom (const Status &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_type_ ()
const ::std::string & type_ () const
void set_type_ (const ::std::string &value)
void set_type_ (const char *value)
void set_type_ (const char *value, size_t size)
::std::string * mutable_type_ ()
::std::string * release_type_ ()
void set_allocated_type_ (::std::string *type_)
void clear_timestamp_ ()
::google::protobuf::uint64 timestamp_ () const
void set_timestamp_ (::google::protobuf::uint64 value)
void clear_run_status_ ()
::x3::Status_RunStatus run_status_ () const
void set_run_status_ (::x3::Status_RunStatus value)
Static Public Member Functions
static const Status & default_instance ()
static bool RunStatus_IsValid (int value)
Static Public Attributes
static const RunStatus Uknown
static const RunStatus Uninit
static const RunStatus Init
static const RunStatus Normal
static const RunStatus Abnormal
static const RunStatus Update
static const RunStatus RunStatus_MIN
static const RunStatus RunStatus_MAX
static const int RunStatus_ARRAYSIZE
static const int kTypeFieldNumber = 1
static const int kTimestampFieldNumber = 2
static const int kRunStatusFieldNumber = 3
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (Status *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::internal::ArenaStringPtr type__
::google::protobuf::uint64 timestamp__
int run_status__
int _cached_size_
Static Private Attributes
static Status * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 3291 of file x3.pb.h.
Member Typedef Documentation
typedef Status_RunStatus x3::Status::RunStatus
Definition at line 3353 of file x3.pb.h.
Constructor & Destructor Documentation
x3::Status::Status ()
Definition at line 11207 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.Status)
 }
x3::Status::~Status () virtual
Definition at line 11234 of file x3.pb.cc.
                 {
   // @@protoc_insertion_point(destructor:x3.Status)
   SharedDtor();
 }
x3::Status::Status (const Status & from)
Definition at line 11217 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.Status)
 }
Member Function Documentation
int x3::Status::ByteSize () const
Definition at line 11404 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.Status)
   int total_size = 0;
   // optional string type_ = 1;
   if (this->type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->type_());
   }
   // optional uint64 timestamp_ = 2;
   if (this->timestamp_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::UInt64Size(
         this->timestamp_());
   }
   // optional .x3.Status.RunStatus run_status_ = 3;
   if (this->run_status_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::EnumSize(this->run_status_());
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::Status::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 11434 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const Status*>(&from));
 }
void x3::Status::Clear ()
Definition at line 11273 of file x3.pb.cc.
Referenced by CopyFrom().
                    {
 // @@protoc_insertion_point(message_clear_start:x3.Status)
 #if defined(__clang__)
 #define ZR_HELPER_(f) \
   _Pragma("clang diagnostic push") \
   _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
   __builtin_offsetof(Status, f) \
   _Pragma("clang diagnostic pop")
 #else
 #define ZR_HELPER_(f) reinterpret_cast<char*>(\
   &reinterpret_cast<Status*>(16)->f)
 #endif
 #define ZR_(first, last) do {\
   ::memset(&first, 0,\
            ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
 } while (0)
   ZR_(timestamp__, run_status__);
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 #undef ZR_HELPER_
 #undef ZR_
 }
void x3::Status::clear_run_status_ () inline
Definition at line 7904 of file x3.pb.h.
{
   run_status__ = 0;
 }
void x3::Status::clear_timestamp_ () inline
Definition at line 7890 of file x3.pb.h.
{
   timestamp__ = GOOGLE_ULONGLONG(0);
 }
void x3::Status::clear_type_ () inline
Definition at line 7846 of file x3.pb.h.
{
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::Status::CopyFrom (const Status & from)
Definition at line 11456 of file x3.pb.cc.
Referenced by operator=().
{
 // @@protoc_insertion_point(class_specific_copy_from_start:x3.Status)
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
const Status & x3::Status::default_instance () static
Definition at line 11254 of file x3.pb.cc.
Referenced by x3::InfoMessage::InitAsDefaultInstance(), and SharedDtor().
{
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   protobuf_AddDesc_x3_2eproto();
 #else
   if (default_instance_ == NULL) pro