XProto Framework API Document: x3::Threshold Class Reference
x3::Threshold Class Reference
#include <x3.pb.h>
Public Member Functions
Threshold ()
virtual ~Threshold ()
Threshold (const Threshold &from)
Threshold & operator= (const Threshold &from)
void Swap (Threshold *other)
Threshold * New () const
Threshold * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const Threshold &from)
void MergeFrom (const Threshold &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_type_ ()
const ::std::string & type_ () const
void set_type_ (const ::std::string &value)
void set_type_ (const char *value)
void set_type_ (const char *value, size_t size)
::std::string * mutable_type_ ()
::std::string * release_type_ ()
void set_allocated_type_ (::std::string *type_)
void clear_value_ ()
float value_ () const
void set_value_ (float value)
Static Public Member Functions
static const Threshold & default_instance ()
Static Public Attributes
static const int kTypeFieldNumber = 1
static const int kValueFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (Threshold *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::internal::ArenaStringPtr type__
float value__
int _cached_size_
Static Private Attributes
static Threshold * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 1487 of file x3.pb.h.
Constructor & Destructor Documentation
x3::Threshold::Threshold ()
Definition at line 5089 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.Threshold)
 }
x3::Threshold::~Threshold () virtual
Definition at line 5115 of file x3.pb.cc.
                       {
   // @@protoc_insertion_point(destructor:x3.Threshold)
   SharedDtor();
 }
x3::Threshold::Threshold (const Threshold & from)
Definition at line 5099 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.Threshold)
 }
Member Function Documentation
int x3::Threshold::ByteSize () const
Definition at line 5243 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.Threshold)
   int total_size = 0;
   // optional string type_ = 1;
   if (this->type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->type_());
   }
   // optional float value_ = 2;
   if (this->value_() != 0) {
     total_size += 1 + 4;
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::Threshold::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 5265 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const Threshold*>(&from));
 }
void x3::Threshold::Clear ()
Definition at line 5154 of file x3.pb.cc.
Referenced by CopyFrom().
                       {
 // @@protoc_insertion_point(message_clear_start:x3.Threshold)
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   value__ = 0;
 }
void x3::Threshold::clear_type_ () inline
Definition at line 6024 of file x3.pb.h.
{
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::Threshold::clear_value_ () inline
Definition at line 6068 of file x3.pb.h.
{
   value__ = 0;
 }
void x3::Threshold::CopyFrom (const Threshold & from)
Definition at line 5284 of file x3.pb.cc.
Referenced by operator=().
{
 // @@protoc_insertion_point(class_specific_copy_from_start:x3.Threshold)
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
const Threshold & x3::Threshold::default_instance () static
Definition at line 5135 of file x3.pb.cc.
Referenced by SharedDtor().
{
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   protobuf_AddDesc_x3_2eproto();
 #else
   if (default_instance_ == NULL) protobuf_AddDesc_x3_2eproto();
 #endif
   return *default_instance_;
 }
void x3::Threshold::DiscardUnknownFields ()
inline ::google::protobuf::Arena* x3::Threshold::GetArenaNoVirtual () const inline private
Definition at line 1537 of file x3.pb.h.
{
     return _arena_ptr_;
   }
int x3::Threshold::GetCachedSize () const inline
Definition at line 1530 of file x3.pb.h.
 { return _cached_size_; }
std::string x3::Threshold::GetTypeName () const
Definition at line 5307 of file x3.pb.cc.
{
   return "x3.Threshold";
 }
void x3::Threshold::InitAsDefaultInstance () private
Definition at line 5095 of file x3.pb.cc.
Referenced by x3::protobuf_AddDesc_x3_2eproto().
{
   _is_default_instance_ = true;
 }
void x3::Threshold::InternalSwap (Threshold * other) private
Definition at line 5300 of file x3.pb.cc.
Referenced by Swap().
{
   type__.Swap(&other->type__);
   std::swap(value__, other->value__);
   _unknown_fields_.Swap(&other->_unknown_fields_);
   std::swap(_cached_size_, other->_cached_size_);
 }
bool x3::Threshold::IsInitialized () const
Definition at line 5291 of file x3.pb.cc.
{
   return true;
 }
inline ::google::protobuf::Arena* x3::Threshold::MaybeArenaPtr () const inline private
Definition at line 1540 of file x3.pb.h.
{
     return _arena_ptr_;
   }
void x3::Threshold::MergeFrom (const Threshold & from)
Definition at line 5270 of file x3.pb.cc.
Referenced by CheckTypeAndMergeFrom(), CopyFrom(), and Threshold().
{