XProto Framework API Document: x3::Point Class Reference
x3::Point Class Reference
#include <x3.pb.h>
Public Member Functions
Point ()
virtual ~Point ()
Point (const Point &from)
Point & operator= (const Point &from)
void Swap (Point *other)
Point * New () const
Point * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const Point &from)
void MergeFrom (const Point &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_x_ ()
float x_ () const
void set_x_ (float value)
void clear_y_ ()
float y_ () const
void set_y_ (float value)
void clear_score_ ()
float score_ () const
void set_score_ (float value)
Static Public Member Functions
static const Point & default_instance ()
Static Public Attributes
static const int kXFieldNumber = 1
static const int kYFieldNumber = 2
static const int kScoreFieldNumber = 3
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (Point *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
float x__
float y__
float score__
int _cached_size_
Static Private Attributes
static Point * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 590 of file x3.pb.h.
Constructor & Destructor Documentation
x3::Point::Point ()
Definition at line 1778 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.Point)
 }
x3::Point::~Point () virtual
Definition at line 1804 of file x3.pb.cc.
               {
   // @@protoc_insertion_point(destructor:x3.Point)
   SharedDtor();
 }
x3::Point::Point (const Point & from)
Definition at line 1788 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.Point)
 }
Member Function Documentation
int x3::Point::ByteSize () const
Definition at line 1963 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.Point)
   int total_size = 0;
   // optional float x_ = 1;
   if (this->x_() != 0) {
     total_size += 1 + 4;
   }
   // optional float y_ = 2;
   if (this->y_() != 0) {
     total_size += 1 + 4;
   }
   // optional float score_ = 3;
   if (this->score_() != 0) {
     total_size += 1 + 4;
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::Point::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 1988 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const Point*>(&from));
 }
void x3::Point::Clear ()
Definition at line 1842 of file x3.pb.cc.
Referenced by CopyFrom().
                   {
 // @@protoc_insertion_point(message_clear_start:x3.Point)
 #if defined(__clang__)
 #define ZR_HELPER_(f) \
   _Pragma("clang diagnostic push") \
   _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
   __builtin_offsetof(Point, f) \
   _Pragma("clang diagnostic pop")
 #else
 #define ZR_HELPER_(f) reinterpret_cast<char*>(\
   &reinterpret_cast<Point*>(16)->f)
 #endif
 #define ZR_(first, last) do {\
   ::memset(&first, 0,\
            ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
 } while (0)
   ZR_(x__, score__);
 #undef ZR_HELPER_
 #undef ZR_
 }
void x3::Point::clear_score_ () inline
Definition at line 5052 of file x3.pb.h.
{
   score__ = 0;
 }
void x3::Point::clear_x_ () inline
Definition at line 5024 of file x3.pb.h.
{
   x__ = 0;
 }
void x3::Point::clear_y_ () inline
Definition at line 5038 of file x3.pb.h.
{
   y__ = 0;
 }
void x3::Point::CopyFrom (const Point & from)
Definition at line 2009 of file x3.pb.cc.
Referenced by operator=().
{
 // @@protoc_insertion_point(class_specific_copy_from_start:x3.Point)
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
const Point & x3::Point::default_instance () static
Definition at line 1823 of file x3.pb.cc.
Referenced by x3::Box::InitAsDefaultInstance(), and SharedDtor().
{
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   protobuf_AddDesc_x3_2eproto();
 #else
   if (default_instance_ == NULL) protobuf_AddDesc_x3_2eproto();
 #endif
   return *default_instance_;
 }
void x3::Point::DiscardUnknownFields ()
inline ::google::protobuf::Arena* x3::Point::GetArenaNoVirtual () const inline private
Definition at line 640 of file x3.pb.h.
{
     return _arena_ptr_;
   }
int x3::Point::GetCachedSize () const inline
Definition at line 633 of file x3.pb.h.
 { return _cached_size_; }
std::string x3::Point::GetTypeName () const
Definition at line 2033 of file x3.pb.cc.
{
   return "x3.Point";
 }
void x3::Point::InitAsDefaultInstance () private
Definition at line 1784 of file x3.pb.cc.
Referenced by x3::protobuf_AddDesc_x3_2eproto().
{
   _is_default_instance_ = true;
 }
void x3::Point::InternalSwap (Point * other) private
Definition at line 2025 of file x3.pb.cc.
Referenced by Swap().
{
   std::swap(x__, other->x__);
   std::swap(y__, other->y__);
   std::swap(score__, other->score__);
   _unknown_fields_.Swap(&other->_unknown_fields_);
   std::swap(_cached_size_, other->_cached_size_);
 }