XProto Framework API Document: x3::FrameMessage Class Reference
x3::FrameMessage Class Reference
#include <x3.pb.h>
Public Member Functions
FrameMessage ()
virtual ~FrameMessage ()
FrameMessage (const FrameMessage &from)
FrameMessage & operator= (const FrameMessage &from)
void Swap (FrameMessage *other)
FrameMessage * New () const
FrameMessage * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const FrameMessage &from)
void MergeFrom (const FrameMessage &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_timestamp_ ()
::google::protobuf::uint64 timestamp_ () const
void set_timestamp_ (::google::protobuf::uint64 value)
bool has_img_ () const
void clear_img_ ()
const ::x3::Image & img_ () const
::x3::Image * mutable_img_ ()
::x3::Image * release_img_ ()
void set_allocated_img_ (::x3::Image *img_)
bool has_smart_msg_ () const
void clear_smart_msg_ ()
const ::x3::SmartLegibleMessage & smart_msg_ () const
::x3::SmartLegibleMessage * mutable_smart_msg_ ()
::x3::SmartLegibleMessage * release_smart_msg_ ()
void set_allocated_smart_msg_ (::x3::SmartLegibleMessage *smart_msg_)
bool has_capture_msg_ () const
void clear_capture_msg_ ()
const ::x3::CaptureMessage & capture_msg_ () const
::x3::CaptureMessage * mutable_capture_msg_ ()
::x3::CaptureMessage * release_capture_msg_ ()
void set_allocated_capture_msg_ (::x3::CaptureMessage *capture_msg_)
bool has_statistics_msg_ () const
void clear_statistics_msg_ ()
const ::x3::StatisticsMessage & statistics_msg_ () const
::x3::StatisticsMessage * mutable_statistics_msg_ ()
::x3::StatisticsMessage * release_statistics_msg_ ()
void set_allocated_statistics_msg_ (::x3::StatisticsMessage *statistics_msg_)
bool has_control_msg_ () const
void clear_control_msg_ ()
const ::x3::ControlMessage & control_msg_ () const
::x3::ControlMessage * mutable_control_msg_ ()
::x3::ControlMessage * release_control_msg_ ()
void set_allocated_control_msg_ (::x3::ControlMessage *control_msg_)
Static Public Member Functions
static const FrameMessage & default_instance ()
Static Public Attributes
static const int kTimestampFieldNumber = 1
static const int kImgFieldNumber = 2
static const int kSmartMsgFieldNumber = 3
static const int kCaptureMsgFieldNumber = 4
static const int kStatisticsMsgFieldNumber = 5
static const int kControlMsgFieldNumber = 6
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (FrameMessage *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::uint64 timestamp__
::x3::Image * img__
::x3::SmartLegibleMessage * smart_msg__
::x3::CaptureMessage * capture_msg__
::x3::StatisticsMessage * statistics_msg__
::x3::ControlMessage * control_msg__
int _cached_size_
Static Private Attributes
static FrameMessage * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 2669 of file x3.pb.h.
Constructor & Destructor Documentation
x3::FrameMessage::FrameMessage ()
Definition at line 9005 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.FrameMessage)
 }
x3::FrameMessage::~FrameMessage () virtual
Definition at line 9064 of file x3.pb.cc.
{
   // @@protoc_insertion_point(destructor:x3.FrameMessage)
   SharedDtor();
 }
x3::FrameMessage::FrameMessage (const FrameMessage & from)
Definition at line 9045 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.FrameMessage)
 }
Member Function Documentation
int x3::FrameMessage::ByteSize () const
Definition at line 9273 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.FrameMessage)
   int total_size = 0;
   // optional fixed64 timestamp_ = 1;
   if (this->timestamp_() != 0) {
     total_size += 1 + 8;
   }
   // optional .x3.Image img_ = 2;
   if (this->has_img_()) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         *this->img__);
   }
   // optional .x3.SmartLegibleMessage smart_msg_ = 3;
   if (this->has_smart_msg_()) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         *this->smart_msg__);
   }
   // optional .x3.CaptureMessage capture_msg_ = 4;
   if (this->has_capture_msg_()) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         *this->capture_msg__);
   }
   // optional .x3.StatisticsMessage Statistics_msg_ = 5;
   if (this->has_statistics_msg_()) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         *this->statistics_msg__);
   }
   // optional .x3.ControlMessage control_msg_ = 6;
   if (this->has_control_msg_()) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         *this->control_msg__);
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
const ::x3::CaptureMessage & x3::FrameMessage::capture_msg_ () const inline
Definition at line 7253 of file x3.pb.h.
Referenced by MergeFrom(), and set_allocated_capture_msg_().
{
   // @@protoc_insertion_point(field_get:x3.FrameMessage.capture_msg_)
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   return capture_msg__ != NULL ? *capture_msg__ : *default_instance().capture_msg__;
 #else
   return capture_msg__ != NULL ? *capture_msg__ : *default_instance_->capture_msg__;
 #endif
 }