XProto Framework API Document: x3::ControlMessage Class Reference
x3::ControlMessage Class Reference
#include <x3.pb.h>
Public Member Functions
ControlMessage ()
virtual ~ControlMessage ()
ControlMessage (const ControlMessage &from)
ControlMessage & operator= (const ControlMessage &from)
void Swap (ControlMessage *other)
ControlMessage * New () const
ControlMessage * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const ControlMessage &from)
void MergeFrom (const ControlMessage &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_type_ ()
const ::std::string & type_ () const
void set_type_ (const ::std::string &value)
void set_type_ (const char *value)
void set_type_ (const char *value, size_t size)
::std::string * mutable_type_ ()
::std::string * release_type_ ()
void set_allocated_type_ (::std::string *type_)
void clear_timestamp_ ()
::google::protobuf::uint64 timestamp_ () const
void set_timestamp_ (::google::protobuf::uint64 value)
void clear_cmd_id_ ()
::google::protobuf::uint64 cmd_id_ () const
void set_cmd_id_ (::google::protobuf::uint64 value)
void clear_value_ ()
const ::std::string & value_ () const
void set_value_ (const ::std::string &value)
void set_value_ (const char *value)
void set_value_ (const void *value, size_t size)
::std::string * mutable_value_ ()
::std::string * release_value_ ()
void set_allocated_value_ (::std::string *value_)
Static Public Member Functions
static const ControlMessage & default_instance ()
Static Public Attributes
static const int kTypeFieldNumber = 1
static const int kTimestampFieldNumber = 2
static const int kCmdIdFieldNumber = 3
static const int kValueFieldNumber = 4
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (ControlMessage *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::internal::ArenaStringPtr type__
::google::protobuf::uint64 timestamp__
::google::protobuf::uint64 cmd_id__
::google::protobuf::internal::ArenaStringPtr value__
int _cached_size_
Static Private Attributes
static ControlMessage * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 2546 of file x3.pb.h.
Constructor & Destructor Documentation
x3::ControlMessage::ControlMessage ()
Definition at line 8565 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.ControlMessage)
 }
x3::ControlMessage::~ControlMessage () virtual
Definition at line 8593 of file x3.pb.cc.
{
   // @@protoc_insertion_point(destructor:x3.ControlMessage)
   SharedDtor();
 }
x3::ControlMessage::ControlMessage (const ControlMessage & from)
Definition at line 8575 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.ControlMessage)
 }
Member Function Documentation
int x3::ControlMessage::ByteSize () const
Definition at line 8782 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.ControlMessage)
   int total_size = 0;
   // optional string type_ = 1;
   if (this->type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->type_());
   }
   // optional fixed64 timestamp_ = 2;
   if (this->timestamp_() != 0) {
     total_size += 1 + 8;
   }
   // optional uint64 cmd_id_ = 3;
   if (this->cmd_id_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::UInt64Size(
         this->cmd_id_());
   }
   // optional bytes value_ = 4;
   if (this->value_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::BytesSize(
         this->value_());
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::ControlMessage::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 8818 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const ControlMessage*>(&from));
 }
void x3::ControlMessage::Clear ()
Definition at line 8633 of file x3.pb.cc.
Referenced by CopyFrom().
{
 // @@protoc_insertion_point(message_clear_start:x3.ControlMessage)
 #if defined(__clang__)
 #define ZR_HELPER_(f) \
   _Pragma("clang diagnostic push") \
   _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
   __builtin_offsetof(ControlMessage, f) \
   _Pragma("clang diagnostic pop")
 #else
 #define ZR_HELPER_(f) reinterpret_cast<char*>(\
   &reinterpret_cast<ControlMessage*>(16)->f)
 #endif
 #define ZR_(first, last) do {\
   ::memset(&first, 0,\
            ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
 } while (0)
   ZR_(timestamp__, cmd_id__);
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   value__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 #undef ZR_HELPER_
 #undef ZR_
 }
void x3::ControlMessage::clear_cmd_id_ () inline
Definition at line 7086 of file x3.pb.h.
{
   cmd_id__ = GOOGLE_ULONGLONG(0);
 }
void x3::ControlMessage::clear_timestamp_ () inline
Definition at line 7072 of file x3.pb.h.
{
   timestamp__ = GOOGLE_ULONGLONG(0);
 }
void x3::ControlMessage::clear_type_ () inline
Definition at line 7028 of file x3.pb.h.
{
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::ControlMessage::clear_value_ () inline
Definition at line 7100 of file x3.pb.h.
{
   value__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
google::protobuf::uint64 x3::ControlMessage::cmd_id_ () const inline
Definition at line 7089 of file x3.pb.h.
Referenced by ByteSize(), MergeFrom(), and SerializeWithCachedSizes().