XProto Framework API Document: x3::Response Class Reference
x3::Response Class Reference
#include <x3.pb.h>
Public Types
typedef Response_Ack Ack
Public Member Functions
Response ()
virtual ~Response ()
Response (const Response &from)
Response & operator= (const Response &from)
void Swap (Response *other)
Response * New () const
Response * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const Response &from)
void MergeFrom (const Response &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_type_ ()
const ::std::string & type_ () const
void set_type_ (const ::std::string &value)
void set_type_ (const char *value)
void set_type_ (const char *value, size_t size)
::std::string * mutable_type_ ()
::std::string * release_type_ ()
void set_allocated_type_ (::std::string *type_)
void clear_timestamp_ ()
::google::protobuf::uint64 timestamp_ () const
void set_timestamp_ (::google::protobuf::uint64 value)
void clear_ack_ ()
::x3::Response_Ack ack_ () const
void set_ack_ (::x3::Response_Ack value)
Static Public Member Functions
static const Response & default_instance ()
static bool Ack_IsValid (int value)
Static Public Attributes
static const Ack Uknown
static const Ack Success
static const Ack Fail
static const Ack Ack_MIN
static const Ack Ack_MAX
static const int Ack_ARRAYSIZE
static const int kTypeFieldNumber = 1
static const int kTimestampFieldNumber = 2
static const int kAckFieldNumber = 3
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (Response *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::internal::ArenaStringPtr type__
::google::protobuf::uint64 timestamp__
int ack__
int _cached_size_
Static Private Attributes
static Response * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 3555 of file x3.pb.h.
Member Typedef Documentation
typedef Response_Ack x3::Response::Ack
Definition at line 3617 of file x3.pb.h.
Constructor & Destructor Documentation
x3::Response::Response ()
Definition at line 11971 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.Response)
 }
x3::Response::~Response () virtual
Definition at line 11998 of file x3.pb.cc.
                     {
   // @@protoc_insertion_point(destructor:x3.Response)
   SharedDtor();
 }
x3::Response::Response (const Response & from)
Definition at line 11981 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.Response)
 }
Member Function Documentation
x3::Response_Ack x3::Response::ack_ () const inline
Definition at line 8059 of file x3.pb.h.
Referenced by ByteSize(), MergeFrom(), and SerializeWithCachedSizes().
{
   // @@protoc_insertion_point(field_get:x3.Response.ack_)
   return static_cast< ::x3::Response_Ack >(ack__);
 }
static bool x3::Response::Ack_IsValid (int value) inline static
Definition at line 3624 of file x3.pb.h.
{
     return Response_Ack_IsValid(value);
   }
int x3::Response::ByteSize () const
Definition at line 12168 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.Response)
   int total_size = 0;
   // optional string type_ = 1;
   if (this->type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->type_());
   }
   // optional uint64 timestamp_ = 2;
   if (this->timestamp_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::UInt64Size(
         this->timestamp_());
   }
   // optional .x3.Response.Ack ack_ = 3;
   if (this->ack_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::EnumSize(this->ack_());
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::Response::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 12198 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const Response*>(&from));
 }
void x3::Response::Clear ()
Definition at line 12037 of file x3.pb.cc.
Referenced by CopyFrom().
                      {
 // @@protoc_insertion_point(message_clear_start:x3.Response)
 #if defined(__clang__)
 #define ZR_HELPER_(f) \
   _Pragma("clang diagnostic push") \
   _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
   __builtin_offsetof(Response, f) \
   _Pragma("clang diagnostic pop")
 #else
 #define ZR_HELPER_(f) reinterpret_cast<char*>(\
   &reinterpret_cast<Response*>(16)->f)
 #endif
 #define ZR_(first, last) do {\
   ::memset(&first, 0,\
            ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
 } while (0)
   ZR_(timestamp__, ack__);
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 #undef ZR_HELPER_
 #undef ZR_
 }
void x3::Response::clear_ack_ () inline
Definition at line 8056 of file x3.pb.h.
{
   ack__ = 0;
 }
void x3::Response::clear_timestamp_ () inline
Definition at line 8042 of file x3.pb.h.
{
   timestamp__ = GOOGLE_ULONGLONG(0);
 }
void x3::Response::clear_type_ () inline
Definition at line 7998 of file x3.pb.h.
{
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::Response::CopyFrom (const Response & from)
Definition at line 12220 of file x3.pb.cc.
Referenced by operator=().
{
 // @@protoc_insertion_point(class_specific_copy_from_start:x3.Response)
   if (&from == this) return;
   Clear();