XProto Framework API Document: x3::MessagePack Class Reference
x3::MessagePack Class Reference
#include <x3.pb.h>
Public Types
typedef MessagePack_Flow Flow
typedef MessagePack_Type Type
Public Member Functions
MessagePack ()
virtual ~MessagePack ()
MessagePack (const MessagePack &from)
MessagePack & operator= (const MessagePack &from)
void Swap (MessagePack *other)
MessagePack * New () const
MessagePack * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const MessagePack &from)
void MergeFrom (const MessagePack &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_flow_ ()
::x3::MessagePack_Flow flow_ () const
void set_flow_ (::x3::MessagePack_Flow value)
void clear_type_ ()
::x3::MessagePack_Type type_ () const
void set_type_ (::x3::MessagePack_Type value)
bool has_addition_ () const
void clear_addition_ ()
const ::x3::Addition & addition_ () const
::x3::Addition * mutable_addition_ ()
::x3::Addition * release_addition_ ()
void set_allocated_addition_ (::x3::Addition *addition_)
void clear_content_ ()
const ::std::string & content_ () const
void set_content_ (const ::std::string &value)
void set_content_ (const char *value)
void set_content_ (const void *value, size_t size)
::std::string * mutable_content_ ()
::std::string * release_content_ ()
void set_allocated_content_ (::std::string *content_)
Static Public Member Functions
static const MessagePack & default_instance ()
static bool Flow_IsValid (int value)
static bool Type_IsValid (int value)
Static Public Attributes
static const Flow Unknown
static const Flow AP2CP
static const Flow CP2AP
static const Flow Flow_MIN
static const Flow Flow_MAX
static const int Flow_ARRAYSIZE
static const Type kUnknown
static const Type kXPlugin
static const Type kXConfig
static const Type Type_MIN
static const Type Type_MAX
static const int Type_ARRAYSIZE
static const int kFlowFieldNumber = 1
static const int kTypeFieldNumber = 2
static const int kAdditionFieldNumber = 3
static const int kContentFieldNumber = 4
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (MessagePack *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
int flow__
int type__
::x3::Addition * addition__
::google::protobuf::internal::ArenaStringPtr content__
int _cached_size_
Static Private Attributes
static MessagePack * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 4308 of file x3.pb.h.
Member Typedef Documentation
typedef MessagePack_Flow x3::MessagePack::Flow
Definition at line 4370 of file x3.pb.h.
typedef MessagePack_Type x3::MessagePack::Type
Definition at line 4387 of file x3.pb.h.
Constructor & Destructor Documentation
x3::MessagePack::MessagePack ()
Definition at line 14289 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.MessagePack)
 }
x3::MessagePack::~MessagePack () virtual
Definition at line 14323 of file x3.pb.cc.
{
   // @@protoc_insertion_point(destructor:x3.MessagePack)
   SharedDtor();
 }
x3::MessagePack::MessagePack (const MessagePack & from)
Definition at line 14305 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.MessagePack)
 }
Member Function Documentation
const ::x3::Addition & x3::MessagePack::addition_ () const inline
Definition at line 8626 of file x3.pb.h.
Referenced by MergeFrom(), and set_allocated_addition_().
{
   // @@protoc_insertion_point(field_get:x3.MessagePack.addition_)
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   return addition__ != NULL ? *addition__ : *default_instance().addition__;
 #else
   return addition__ != NULL ? *addition__ : *default_instance_->addition__;
 #endif
 }
int x3::MessagePack::ByteSize () const
Definition at line 14509 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.MessagePack)
   int total_size = 0;
   // optional .x3.MessagePack.Flow flow_ = 1;
   if (this->flow_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::EnumSize(this->flow_());
   }
   // optional .x3.MessagePack.Type type_ = 2;
   if (this->type_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::EnumSize(this->type_());
   }
   // optional .x3.Addition addition_ = 3;
   if (this->has_addition_()) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         *this->addition__);
   }
   // optional bytes content_ = 4;
   if (this->content_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::BytesSize(
         this->content_());
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::MessagePack::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 14545 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const MessagePack*>(&from));
 }
void x3::MessagePack::Clear ()
Definition at line 14363 of file x3.pb.cc.
Referenced by CopyFrom().
{
 // @@protoc_insertion_point(message_clear_start:x3.MessagePack)
 #if defined(__clang__)
 #define ZR_HELPER_(f) \
   _Pragma("clang diagnostic push") \
   _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
   __builtin_offsetof(MessagePack, f) \