XProto Framework API Document: x3::Points Class Reference
x3::Points Class Reference
#include <x3.pb.h>
Public Member Functions
Points ()
virtual ~Points ()
Points (const Points &from)
Points & operator= (const Points &from)
void Swap (Points *other)
Points * New () const
Points * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const Points &from)
void MergeFrom (const Points &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_type_ ()
const ::std::string & type_ () const
void set_type_ (const ::std::string &value)
void set_type_ (const char *value)
void set_type_ (const char *value, size_t size)
::std::string * mutable_type_ ()
::std::string * release_type_ ()
void set_allocated_type_ (::std::string *type_)
int points__size () const
void clear_points_ ()
const ::x3::Point & points_ (int index) const
::x3::Point * mutable_points_ (int index)
::x3::Point * add_points_ ()
::google::protobuf::RepeatedPtrField
< ::x3::Point > * mutable_points_ ()
const
::google::protobuf::RepeatedPtrField
< ::x3::Point > & points_ () const
void clear_name_ ()
const ::std::string & name_ () const
void set_name_ (const ::std::string &value)
void set_name_ (const char *value)
void set_name_ (const char *value, size_t size)
::std::string * mutable_name_ ()
::std::string * release_name_ ()
void set_allocated_name_ (::std::string *name_)
void clear_specific_type_ ()
const ::std::string & specific_type_ () const
void set_specific_type_ (const ::std::string &value)
void set_specific_type_ (const char *value)
void set_specific_type_ (const char *value, size_t size)
::std::string * mutable_specific_type_ ()
::std::string * release_specific_type_ ()
void set_allocated_specific_type_ (::std::string *specific_type_)
Static Public Member Functions
static const Points & default_instance ()
Static Public Attributes
static const int kTypeFieldNumber = 1
static const int kPointsFieldNumber = 2
static const int kNameFieldNumber = 3
static const int kSpecificTypeFieldNumber = 4
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (Points *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::internal::ArenaStringPtr type__
::google::protobuf::RepeatedPtrField
< ::x3::Point > points__
::google::protobuf::internal::ArenaStringPtr name__
::google::protobuf::internal::ArenaStringPtr specific_type__
int _cached_size_
Static Private Attributes
static Points * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 696 of file x3.pb.h.
Constructor & Destructor Documentation
x3::Points::Points ()
Definition at line 2093 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.Points)
 }
x3::Points::~Points () virtual
Definition at line 2120 of file x3.pb.cc.
                 {
   // @@protoc_insertion_point(destructor:x3.Points)
   SharedDtor();
 }
x3::Points::Points (const Points & from)
Definition at line 2103 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.Points)
 }
Member Function Documentation
x3::Point * x3::Points::add_points_ () inline
Definition at line 5128 of file x3.pb.h.
Referenced by MergePartialFromCodedStream().
{
   // @@protoc_insertion_point(field_add:x3.Points.points_)
   return points__.Add();
 }
int x3::Points::ByteSize () const
Definition at line 2309 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.Points)
   int total_size = 0;
   // optional string type_ = 1;
   if (this->type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->type_());
   }
   // optional string name_ = 3;
   if (this->name_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->name_());
   }
   // optional string specific_type_ = 4;
   if (this->specific_type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->specific_type_());
   }
   // repeated .x3.Point points_ = 2;
   total_size += 1 * this->points__size();
   for (int i = 0; i < this->points__size(); i++) {
     total_size +=
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         this->points_(i));
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::Points::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 2348 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const Points*>(&from));
 }
void x3::Points::Clear ()
Definition at line 2161 of file x3.pb.cc.
Referenced by CopyFrom().
                    {
 // @@protoc_insertion_point(message_clear_start:x3.Points)
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   name__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   specific_type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   points__.Clear();
 }
void x3::Points::clear_name_ () inline
Definition at line 5144 of file x3.pb.h.
{
   name__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::Points::clear_points_ () inline
Definition at line 5117 of file x3.pb.h.
{
   points__.Clear();
 }
void x3::Points::clear_specific_type_ () inline
Definition at line 5188 of file x3.pb.h.
{
   specific_type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::Points::clear_type_ ()