XProto Framework API Document: x3::Enable Class Reference
x3::Enable Class Reference
#include <x3.pb.h>
Public Member Functions
Enable ()
virtual ~Enable ()
Enable (const Enable &from)
Enable & operator= (const Enable &from)
void Swap (Enable *other)
Enable * New () const
Enable * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const Enable &from)
void MergeFrom (const Enable &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_type_ ()
const ::std::string & type_ () const
void set_type_ (const ::std::string &value)
void set_type_ (const char *value)
void set_type_ (const char *value, size_t size)
::std::string * mutable_type_ ()
::std::string * release_type_ ()
void set_allocated_type_ (::std::string *type_)
void clear_value_ ()
bool value_ () const
void set_value_ (bool value)
Static Public Member Functions
static const Enable & default_instance ()
Static Public Attributes
static const int kTypeFieldNumber = 1
static const int kValueFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (Enable *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::internal::ArenaStringPtr type__
bool value__
int _cached_size_
Static Private Attributes
static Enable * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 1383 of file x3.pb.h.
Constructor & Destructor Documentation
x3::Enable::Enable ()
Definition at line 4797 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.Enable)
 }
x3::Enable::~Enable () virtual
Definition at line 4823 of file x3.pb.cc.
                 {
   // @@protoc_insertion_point(destructor:x3.Enable)
   SharedDtor();
 }
x3::Enable::Enable (const Enable & from)
Definition at line 4807 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.Enable)
 }
Member Function Documentation
int x3::Enable::ByteSize () const
Definition at line 4951 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.Enable)
   int total_size = 0;
   // optional string type_ = 1;
   if (this->type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->type_());
   }
   // optional bool value_ = 2;
   if (this->value_() != 0) {
     total_size += 1 + 1;
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::Enable::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 4973 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const Enable*>(&from));
 }
void x3::Enable::Clear ()
Definition at line 4862 of file x3.pb.cc.
Referenced by CopyFrom().
                    {
 // @@protoc_insertion_point(message_clear_start:x3.Enable)
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   value__ = false;
 }
void x3::Enable::clear_type_ () inline
Definition at line 5962 of file x3.pb.h.
{
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::Enable::clear_value_ () inline
Definition at line 6006 of file x3.pb.h.
{
   value__ = false;
 }
void x3::Enable::CopyFrom (const Enable & from)
Definition at line 4992 of file x3.pb.cc.
Referenced by operator=().
{
 // @@protoc_insertion_point(class_specific_copy_from_start:x3.Enable)
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
const Enable & x3::Enable::default_instance () static
Definition at line 4843 of file x3.pb.cc.
Referenced by x3::Capability::InitAsDefaultInstance(), and SharedDtor().
{
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   protobuf_AddDesc_x3_2eproto();
 #else
   if (default_instance_ == NULL) protobuf_AddDesc_x3_2eproto();
 #endif
   return *default_instance_;
 }
void x3::Enable::DiscardUnknownFields ()
inline ::google::protobuf::Arena* x3::Enable::GetArenaNoVirtual () const inline private
Definition at line 1433 of file x3.pb.h.
{
     return _arena_ptr_;
   }
int x3::Enable::GetCachedSize () const inline
Definition at line 1426 of file x3.pb.h.
 { return _cached_size_; }
std::string x3::Enable::GetTypeName () const
Definition at line 5015 of file x3.pb.cc.
{
   return "x3.Enable";
 }
void x3::Enable::InitAsDefaultInstance () private
Definition at line 4803 of file x3.pb.cc.
Referenced by x3::protobuf_AddDesc_x3_2eproto().
{
   _is_default_instance_ = true;
 }
void x3::Enable::InternalSwap (Enable * other) private
Definition at line 5008 of file x3.pb.cc.
Referenced by Swap().
{
   type__.Swap(&other->type__);
   std::swap(value__, other->value__);
   _unknown_fields_.Swap(&other->_unknown_fields_);
   std::swap(_cached_size_, other->_cached_size_);
 }
bool x3::Enable::IsInitialized () const
Definition at line 4999 of file x3.pb.cc.
{
   return true;
 }
inline ::google::protobuf::Arena* x3::Enable::MaybeArenaPtr () const inline private
Definition at line 1436 of file x3.pb.h.
{
     return _arena_ptr_;
   }
void x3::Enable::MergeFrom (const Enable & from)
Definition at line 4978 of file x3.pb.cc.
Referenced by CheckTypeAndMergeFrom(), CopyFrom(), and Enable().
{
 // @@protoc_insertion_point(class_specific_merge_from_start:x3.Enable)
   if (GOOGLE_PREDICT_FALSE(&from == this)) {
     ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
   }