XProto Framework API Document: x3::CaptureMessage Class Reference
x3::CaptureMessage Class Reference
#include <x3.pb.h>
Public Member Functions
CaptureMessage ()
virtual ~CaptureMessage ()
CaptureMessage (const CaptureMessage &from)
CaptureMessage & operator= (const CaptureMessage &from)
void Swap (CaptureMessage *other)
CaptureMessage * New () const
CaptureMessage * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const CaptureMessage &from)
void MergeFrom (const CaptureMessage &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
int targets__size () const
void clear_targets_ ()
const ::x3::CaptureTarget & targets_ (int index) const
::x3::CaptureTarget * mutable_targets_ (int index)
::x3::CaptureTarget * add_targets_ ()
::google::protobuf::RepeatedPtrField
< ::x3::CaptureTarget > * mutable_targets_ ()
const
::google::protobuf::RepeatedPtrField
< ::x3::CaptureTarget > & targets_ () const
Static Public Member Functions
static const CaptureMessage & default_instance ()
Static Public Attributes
static const int kTargetsFieldNumber = 1
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (CaptureMessage *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::RepeatedPtrField
< ::x3::CaptureTarget > targets__
int _cached_size_
Static Private Attributes
static CaptureMessage * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 2350 of file x3.pb.h.
Constructor & Destructor Documentation
x3::CaptureMessage::CaptureMessage ()
Definition at line 8116 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.CaptureMessage)
 }
x3::CaptureMessage::~CaptureMessage () virtual
Definition at line 8139 of file x3.pb.cc.
{
   // @@protoc_insertion_point(destructor:x3.CaptureMessage)
   SharedDtor();
 }
x3::CaptureMessage::CaptureMessage (const CaptureMessage & from)
Definition at line 8126 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.CaptureMessage)
 }
Member Function Documentation
x3::CaptureTarget * x3::CaptureMessage::add_targets_ () inline
Definition at line 6974 of file x3.pb.h.
Referenced by MergePartialFromCodedStream().
{
   // @@protoc_insertion_point(field_add:x3.CaptureMessage.targets_)
   return targets__.Add();
 }
int x3::CaptureMessage::ByteSize () const
Definition at line 8241 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.CaptureMessage)
   int total_size = 0;
   // repeated .x3.CaptureTarget targets_ = 1;
   total_size += 1 * this->targets__size();
   for (int i = 0; i < this->targets__size(); i++) {
     total_size +=
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         this->targets_(i));
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::CaptureMessage::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 8259 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const CaptureMessage*>(&from));
 }
void x3::CaptureMessage::Clear ()
Definition at line 8177 of file x3.pb.cc.
Referenced by CopyFrom().
{
 // @@protoc_insertion_point(message_clear_start:x3.CaptureMessage)
   targets__.Clear();
 }
void x3::CaptureMessage::clear_targets_ () inline
Definition at line 6963 of file x3.pb.h.
{
   targets__.Clear();
 }
void x3::CaptureMessage::CopyFrom (const CaptureMessage & from)
Definition at line 8272 of file x3.pb.cc.
Referenced by operator=().
{
 // @@protoc_insertion_point(class_specific_copy_from_start:x3.CaptureMessage)
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
const CaptureMessage & x3::CaptureMessage::default_instance () static
Definition at line 8158 of file x3.pb.cc.
Referenced by x3::FrameMessage::InitAsDefaultInstance(), and SharedDtor().
{
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   protobuf_AddDesc_x3_2eproto();
 #else
   if (default_instance_ == NULL) protobuf_AddDesc_x3_2eproto();
 #endif
   return *default_instance_;
 }
void x3::CaptureMessage::DiscardUnknownFields ()
inline ::google::protobuf::Arena* x3::CaptureMessage::GetArenaNoVirtual () const inline private
Definition at line 2400 of file x3.pb.h.
{
     return _arena_ptr_;
   }
int x3::CaptureMessage::GetCachedSize () const inline
Definition at line 2393 of file x3.pb.h.
 { return _cached_size_; }
std::string x3::CaptureMessage::GetTypeName () const
Definition at line 8294 of file x3.pb.cc.
{
   return "x3.CaptureMessage";
 }
void x3::CaptureMessage::InitAsDefaultInstance () private
Definition at line 8122 of file x3.pb.cc.
Referenced by x3::protobuf_AddDesc_x3_2eproto().
{
   _is_default_instance_ = true;
 }
void x3::CaptureMessage::InternalSwap (CaptureMessage * other) private
Definition at line 8288 of file x3.pb.cc.
Referenced by Swap().
{
   targets__.UnsafeArenaSwap(&other->targets__);
   _unknown_fields_.Swap(&other->_unknown_fields_);
   std::swap(_cached_size_, other->_cached_size_);
 }
bool x3::CaptureMessage::IsInitialized () const
Definition at line 8279 of file x3.pb.cc.
{
   return true;
 }
inline ::google::protobuf::Arena* x3::CaptureMessage::MaybeArenaPtr () const inline private
Definition at line 2403 of file x3.pb.h.
{
     return _arena_ptr_;
   }
void x3::CaptureMessage::MergeFrom (const CaptureMessage & from)
Definition at line 8264 of file x3.pb.cc.
Referenced by CaptureMessage(), CheckTypeAndMergeFrom(), and CopyFrom().
{
 // @@protoc_insertion_point(class_specific_merge_from_start:x3.CaptureMessage)
   if (GOOGLE_PREDICT_FALSE(&from == this)) {
     ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
   }
   targets__.MergeFrom(from.targets__);
 }