XProto Framework API Document: x3::Capability Class Reference
x3::Capability Class Reference
#include <x3.pb.h>
Public Member Functions
Capability ()
virtual ~Capability ()
Capability (const Capability &from)
Capability & operator= (const Capability &from)
void Swap (Capability *other)
Capability * New () const
Capability * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const Capability &from)
void MergeFrom (const Capability &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_type_ ()
const ::std::string & type_ () const
void set_type_ (const ::std::string &value)
void set_type_ (const char *value)
void set_type_ (const char *value, size_t size)
::std::string * mutable_type_ ()
::std::string * release_type_ ()
void set_allocated_type_ (::std::string *type_)
bool has_cap_array_ () const
void clear_cap_array_ ()
const ::x3::Enable & cap_array_ () const
::x3::Enable * mutable_cap_array_ ()
::x3::Enable * release_cap_array_ ()
void set_allocated_cap_array_ (::x3::Enable *cap_array_)
Static Public Member Functions
static const Capability & default_instance ()
Static Public Attributes
static const int kTypeFieldNumber = 1
static const int kCapArrayFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (Capability *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::internal::ArenaStringPtr type__
::x3::Enable * cap_array__
int _cached_size_
Static Private Attributes
static Capability * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 2939 of file x3.pb.h.
Constructor & Destructor Documentation
x3::Capability::Capability ()
Definition at line 10080 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.Capability)
 }
x3::Capability::~Capability () virtual
Definition at line 10112 of file x3.pb.cc.
{
   // @@protoc_insertion_point(destructor:x3.Capability)
   SharedDtor();
 }
x3::Capability::Capability (const Capability & from)
Definition at line 10096 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.Capability)
 }
Member Function Documentation
int x3::Capability::ByteSize () const
Definition at line 10241 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.Capability)
   int total_size = 0;
   // optional string type_ = 1;
   if (this->type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->type_());
   }
   // optional .x3.Enable cap_array_ = 2;
   if (this->has_cap_array_()) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         *this->cap_array__);
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
const ::x3::Enable & x3::Capability::cap_array_ () const inline
Definition at line 7577 of file x3.pb.h.
Referenced by MergeFrom(), and set_allocated_cap_array_().
{
   // @@protoc_insertion_point(field_get:x3.Capability.cap_array_)
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   return cap_array__ != NULL ? *cap_array__ : *default_instance().cap_array__;
 #else
   return cap_array__ != NULL ? *cap_array__ : *default_instance_->cap_array__;
 #endif
 }
void x3::Capability::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 10265 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const Capability*>(&from));
 }
void x3::Capability::Clear ()
Definition at line 10152 of file x3.pb.cc.
Referenced by CopyFrom().
{
 // @@protoc_insertion_point(message_clear_start:x3.Capability)
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   if (GetArenaNoVirtual() == NULL && cap_array__ != NULL) delete cap_array__;
   cap_array__ = NULL;
 }
void x3::Capability::clear_cap_array_ () inline
Definition at line 7573 of file x3.pb.h.
{
   if (GetArenaNoVirtual() == NULL && cap_array__ != NULL) delete cap_array__;
   cap_array__ = NULL;
 }
void x3::Capability::clear_type_ () inline
Definition at line 7526 of file x3.pb.h.
{
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::Capability::CopyFrom (const Capability & from)
Definition at line 10284 of file x3.pb.cc.
Referenced by operator=().
{
 // @@protoc_insertion_point(class_specific_copy_from_start:x3.Capability)
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
const Capability & x3::Capability::default_instance () static
Definition at line 10133 of file x3.pb.cc.
Referenced by cap_array_(), and SharedDtor().
{
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   protobuf_AddDesc_x3_2eproto();
 #else
   if (default_instance_ == NULL) protobuf_AddDesc_x3_2eproto();
 #endif
   return *default_instance_;
 }
void x3::Capability::DiscardUnknownFields ()
inline ::google::protobuf::Arena* x3::Capability::GetArenaNoVirtual () const inline private
Definition at line 2989 of file x3.pb.h.
Referenced by Clear(), and clear_cap_array_().
{
     return _arena_ptr_;
   }
int x3::Capability::GetCachedSize () const inline
Definition at line 2982 of file x3.pb.h.
 { return _cached_size_; }
std::string x3::Capability::GetTypeName () const
Definition at line 10307 of file x3.pb.cc.
{
   return "x3.Capability";
 }