XProto Framework API Document: x3::StatisticsMessage Class Reference
x3::StatisticsMessage Class Reference
#include <x3.pb.h>
Public Member Functions
StatisticsMessage ()
virtual ~StatisticsMessage ()
StatisticsMessage (const StatisticsMessage &from)
StatisticsMessage & operator= (const StatisticsMessage &from)
void Swap (StatisticsMessage *other)
StatisticsMessage * New () const
StatisticsMessage * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const StatisticsMessage &from)
void MergeFrom (const StatisticsMessage &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
int attributes__size () const
void clear_attributes_ ()
const ::x3::Attributes & attributes_ (int index) const
::x3::Attributes * mutable_attributes_ (int index)
::x3::Attributes * add_attributes_ ()
::google::protobuf::RepeatedPtrField
< ::x3::Attributes > * mutable_attributes_ ()
const
::google::protobuf::RepeatedPtrField
< ::x3::Attributes > & attributes_ () const
Static Public Member Functions
static const StatisticsMessage & default_instance ()
Static Public Attributes
static const int kAttributesFieldNumber = 1
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (StatisticsMessage *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::RepeatedPtrField
< ::x3::Attributes > attributes__
int _cached_size_
Static Private Attributes
static StatisticsMessage * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 2448 of file x3.pb.h.
Constructor & Destructor Documentation
x3::StatisticsMessage::StatisticsMessage ()
Definition at line 8339 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.StatisticsMessage)
 }
x3::StatisticsMessage::~StatisticsMessage () virtual
Definition at line 8362 of file x3.pb.cc.
{
   // @@protoc_insertion_point(destructor:x3.StatisticsMessage)
   SharedDtor();
 }
x3::StatisticsMessage::StatisticsMessage (const StatisticsMessage & from)
Definition at line 8349 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.StatisticsMessage)
 }
Member Function Documentation
x3::Attributes * x3::StatisticsMessage::add_attributes_ () inline
Definition at line 7008 of file x3.pb.h.
Referenced by MergePartialFromCodedStream().
{
   // @@protoc_insertion_point(field_add:x3.StatisticsMessage.attributes_)
   return attributes__.Add();
 }
const ::x3::Attributes & x3::StatisticsMessage::attributes_ (int index) const inline
Definition at line 7000 of file x3.pb.h.
{
   // @@protoc_insertion_point(field_get:x3.StatisticsMessage.attributes_)
   return attributes__.Get(index);
 }
const ::google::protobuf::RepeatedPtrField<::x3::Attributes > & x3::StatisticsMessage::attributes_ () const inline
Definition at line 7018 of file x3.pb.h.
Referenced by ByteSize(), and SerializeWithCachedSizes().
{
   // @@protoc_insertion_point(field_list:x3.StatisticsMessage.attributes_)
   return attributes__;
 }
int x3::StatisticsMessage::attributes__size () const inline
Definition at line 6994 of file x3.pb.h.
Referenced by ByteSize(), and SerializeWithCachedSizes().
{
   return attributes__.size();
 }
int x3::StatisticsMessage::ByteSize () const
Definition at line 8464 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.StatisticsMessage)
   int total_size = 0;
   // repeated .x3.Attributes attributes_ = 1;
   total_size += 1 * this->attributes__size();
   for (int i = 0; i < this->attributes__size(); i++) {
     total_size +=
       ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
         this->attributes_(i));
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::StatisticsMessage::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 8482 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const StatisticsMessage*>(&from));
 }
void x3::StatisticsMessage::Clear ()
Definition at line 8400 of file x3.pb.cc.
Referenced by CopyFrom().
{
 // @@protoc_insertion_point(message_clear_start:x3.StatisticsMessage)
   attributes__.Clear();
 }
void x3::StatisticsMessage::clear_attributes_ () inline
Definition at line 6997 of file x3.pb.h.
{
   attributes__.Clear();
 }
void x3::StatisticsMessage::CopyFrom (const StatisticsMessage & from)
Definition at line 8495 of file x3.pb.cc.
Referenced by operator=().
{
 // @@protoc_insertion_point(class_specific_copy_from_start:x3.StatisticsMessage)
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
const StatisticsMessage & x3::StatisticsMessage::default_instance () static
Definition at line 8381 of file x3.pb.cc.
Referenced by x3::FrameMessage::InitAsDefaultInstance(), and SharedDtor().
{
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   protobuf_AddDesc_x3_2eproto();
 #else
   if (default_instance_ == NULL) protobuf_AddDesc_x3_2eproto();
 #endif
   return *default_instance_;
 }
void x3::StatisticsMessage::DiscardUnknownFields ()
inline ::google::protobuf::Arena* x3::StatisticsMessage::GetArenaNoVirtual () const inline private
Definition at line 2498 of file x3.pb.h.
{
     return _arena_ptr_;
   }
int x3::StatisticsMessage::GetCachedSize () const inline
Definition at line 2491 of file x3.pb.h.
 { return _cached_size_; }
std::string x3::StatisticsMessage::GetTypeName () const
Definition at line 8517 of file x3.pb.cc.
{
   return "x3.StatisticsMessage";
 }
void x3::StatisticsMessage::InitAsDefaultInstance () private
Definition at line 8345 of file x3.pb.cc.
Referenced by x3::protobuf_AddDesc_x3_2eproto().
{
   _is_default_instance_ = true;
 }
void x3::StatisticsMessage::InternalSwap (StatisticsMessage * other) private
Definition at line 8511 of file x3.pb.cc.
Referenced by Swap().
{
   attributes__.UnsafeArenaSwap(&other->attributes__);
   _unknown_fields_.Swap(&other->_unknown_fields_);
   std::swap(