XProto Framework API Document: x3::LogLevel Class Reference
x3::LogLevel Class Reference
#include <x3.pb.h>
Public Types
typedef LogLevel_Level Level
Public Member Functions
LogLevel ()
virtual ~LogLevel ()
LogLevel (const LogLevel &from)
LogLevel & operator= (const LogLevel &from)
void Swap (LogLevel *other)
LogLevel * New () const
LogLevel * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const LogLevel &from)
void MergeFrom (const LogLevel &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_type_ ()
const ::std::string & type_ () const
void set_type_ (const ::std::string &value)
void set_type_ (const char *value)
void set_type_ (const char *value, size_t size)
::std::string * mutable_type_ ()
::std::string * release_type_ ()
void set_allocated_type_ (::std::string *type_)
void clear_level_ ()
::x3::LogLevel_Level level_ () const
void set_level_ (::x3::LogLevel_Level value)
Static Public Member Functions
static const LogLevel & default_instance ()
static bool Level_IsValid (int value)
Static Public Attributes
static const Level X2_DEBUG
static const Level X2_INFO
static const Level X2_NOTICE
static const Level X2_WARN
static const Level X2_ERROR
static const Level X2_FATAL
static const Level X2_NONE
static const Level Level_MIN
static const Level Level_MAX
static const int Level_ARRAYSIZE
static const int kTypeFieldNumber = 1
static const int kLevelFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (LogLevel *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::internal::ArenaStringPtr type__
int level__
int _cached_size_
Static Private Attributes
static LogLevel * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 3683 of file x3.pb.h.
Member Typedef Documentation
typedef LogLevel_Level x3::LogLevel::Level
Definition at line 3745 of file x3.pb.h.
Constructor & Destructor Documentation
x3::LogLevel::LogLevel ()
Definition at line 12359 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.LogLevel)
 }
x3::LogLevel::~LogLevel () virtual
Definition at line 12385 of file x3.pb.cc.
                     {
   // @@protoc_insertion_point(destructor:x3.LogLevel)
   SharedDtor();
 }
x3::LogLevel::LogLevel (const LogLevel & from)
Definition at line 12369 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.LogLevel)
 }
Member Function Documentation
int x3::LogLevel::ByteSize () const
Definition at line 12515 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.LogLevel)
   int total_size = 0;
   // optional string type_ = 1;
   if (this->type_().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->type_());
   }
   // optional .x3.LogLevel.Level level_ = 2;
   if (this->level_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::EnumSize(this->level_());
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::LogLevel::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 12538 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const LogLevel*>(&from));
 }
void x3::LogLevel::Clear ()
Definition at line 12424 of file x3.pb.cc.
Referenced by CopyFrom().
                      {
 // @@protoc_insertion_point(message_clear_start:x3.LogLevel)
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   level__ = 0;
 }
void x3::LogLevel::clear_level_ () inline
Definition at line 8118 of file x3.pb.h.
{
   level__ = 0;
 }
void x3::LogLevel::clear_type_ () inline
Definition at line 8074 of file x3.pb.h.
{
   type__.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
void x3::LogLevel::CopyFrom (const LogLevel & from)
Definition at line 12557 of file x3.pb.cc.
Referenced by operator=().
{
 // @@protoc_insertion_point(class_specific_copy_from_start:x3.LogLevel)
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
const LogLevel & x3::LogLevel::default_instance () static
Definition at line 12405 of file x3.pb.cc.
Referenced by x3::InfoMessage::InitAsDefaultInstance(), and SharedDtor().
{
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   protobuf_AddDesc_x3_2eproto();
 #else
   if (default_instance_ == NULL) protobuf_AddDesc_x3_2eproto();
 #endif
   return *default_instance_;
 }
void x3::LogLevel::DiscardUnknownFields ()
inline ::google::protobuf::Arena* x3::LogLevel::GetArenaNoVirtual () const inline private
Definition at line 3733 of file x3.pb.h.
{
     return _arena_ptr_;
   }
int x3::LogLevel::GetCachedSize () const inline
Definition at line 3726 of file x3.pb.h.
 { return _cached_size_; }
std::string x3::LogLevel::GetTypeName () const
Definition at line 12580 of file x3.pb.cc.
{
   return "x3.LogLevel";
 }
void x3::LogLevel::InitAsDefaultInstance () private
Definition at line 12365 of file x3.pb.cc.
Referenced by x3::protobuf_AddDesc_x3_2eproto().
{
   _is_default_instance_ = true;
 }
void x3::LogLevel::InternalSwap (LogLevel * other)