XProto Framework API Document: x3::Frame Class Reference
x3::Frame Class Reference
#include <x3.pb.h>
Public Types
typedef Frame_FrameType FrameType
Public Member Functions
Frame ()
virtual ~Frame ()
Frame (const Frame &from)
Frame & operator= (const Frame &from)
void Swap (Frame *other)
Frame * New () const
Frame * New (::google::protobuf::Arena *arena) const
void CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite &from)
void CopyFrom (const Frame &from)
void MergeFrom (const Frame &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
void DiscardUnknownFields ()
int GetCachedSize () const
::std::string GetTypeName () const
void clear_sequence_id_ ()
::google::protobuf::uint64 sequence_id_ () const
void set_sequence_id_ (::google::protobuf::uint64 value)
void clear_timestamp_ ()
::google::protobuf::uint64 timestamp_ () const
void set_timestamp_ (::google::protobuf::uint64 value)
void clear_frame_type_ ()
::x3::Frame_FrameType frame_type_ () const
void set_frame_type_ (::x3::Frame_FrameType value)
Static Public Member Functions
static const Frame & default_instance ()
static bool FrameType_IsValid (int value)
Static Public Attributes
static const FrameType Unkown
static const FrameType SmartFrame
static const FrameType DropFrame
static const FrameType ErrorFrame
static const FrameType FrameType_MIN
static const FrameType FrameType_MAX
static const int FrameType_ARRAYSIZE
static const int kSequenceIdFieldNumber = 1
static const int kTimestampFieldNumber = 2
static const int kFrameTypeFieldNumber = 3
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InternalSwap (Frame *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
inline::google::protobuf::Arena * MaybeArenaPtr () const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::internal::ArenaStringPtr _unknown_fields_
::google::protobuf::Arena * _arena_ptr_
bool _is_default_instance_
::google::protobuf::uint64 sequence_id__
::google::protobuf::uint64 timestamp__
int frame_type__
int _cached_size_
Static Private Attributes
static Frame * default_instance_ = NULL
Friends
void protobuf_AddDesc_x3_2eproto ()
void protobuf_AssignDesc_x3_2eproto ()
void protobuf_ShutdownFile_x3_2eproto ()
Detailed Description
Definition at line 3976 of file x3.pb.h.
Member Typedef Documentation
typedef Frame_FrameType x3::Frame::FrameType
Definition at line 4038 of file x3.pb.h.
Constructor & Destructor Documentation
x3::Frame::Frame ()
Definition at line 13359 of file x3.pb.cc.
Referenced by New().
   : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
   SharedCtor();
   // @@protoc_insertion_point(constructor:x3.Frame)
 }
x3::Frame::~Frame () virtual
Definition at line 13385 of file x3.pb.cc.
               {
   // @@protoc_insertion_point(destructor:x3.Frame)
   SharedDtor();
 }
x3::Frame::Frame (const Frame & from)
Definition at line 13369 of file x3.pb.cc.
   : ::google::protobuf::MessageLite(),
     _arena_ptr_(NULL) {
   SharedCtor();
   MergeFrom(from);
   // @@protoc_insertion_point(copy_constructor:x3.Frame)
 }
Member Function Documentation
int x3::Frame::ByteSize () const
Definition at line 13546 of file x3.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:x3.Frame)
   int total_size = 0;
   // optional uint64 sequence_id_ = 1;
   if (this->sequence_id_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::UInt64Size(
         this->sequence_id_());
   }
   // optional uint64 timestamp_ = 2;
   if (this->timestamp_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::UInt64Size(
         this->timestamp_());
   }
   // optional .x3.Frame.FrameType frame_type_ = 3;
   if (this->frame_type_() != 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::EnumSize(this->frame_type_());
   }
   GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
   _cached_size_ = total_size;
   GOOGLE_SAFE_CONCURRENT_WRITES_END();
   return total_size;
 }
void x3::Frame::CheckTypeAndMergeFrom (const ::google::protobuf::MessageLite & from)
Definition at line 13576 of file x3.pb.cc.
{
   MergeFrom(*::google::protobuf::down_cast<const Frame*>(&from));
 }
void x3::Frame::Clear ()
Definition at line 13423 of file x3.pb.cc.
Referenced by CopyFrom().
                   {
 // @@protoc_insertion_point(message_clear_start:x3.Frame)
 #if defined(__clang__)
 #define ZR_HELPER_(f) \
   _Pragma("clang diagnostic push") \
   _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
   __builtin_offsetof(Frame, f) \
   _Pragma("clang diagnostic pop")
 #else
 #define ZR_HELPER_(f) reinterpret_cast<char*>(\
   &reinterpret_cast<Frame*>(16)->f)
 #endif
 #define ZR_(first, last) do {\
   ::memset(&first, 0,\
            ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
 } while (0)
   ZR_(sequence_id__, frame_type__);
 #undef ZR_HELPER_
 #undef ZR_
 }
void x3::Frame::clear_frame_type_ () inline
Definition at line 8426 of file x3.pb.h.
{
   frame_type__ = 0;
 }
void x3::Frame::clear_sequence_id_ () inline
Definition at line 8398 of file x3.pb.h.
{
   sequence_id__ = GOOGLE_ULONGLONG(0);
 }
void x3::Frame::clear_timestamp_ () inline
Definition at line 8412 of file x3.pb.h.
{
   timestamp__ = GOOGLE_ULONGLONG(0);
 }
void x3::Frame::CopyFrom (const Frame & from)
Definition at line 13597 of file x3.pb.cc.
Referenced by operator=().
{
 // @@protoc_insertion_point(class_specific_copy_from_start:x3.Frame)
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
const Frame & x3::Frame::default_instance () static
Definition at line 13404 of file x3.pb.cc.
Referenced by x3::Addition::InitAsDefaultInstance(), and SharedDtor().
{
 #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
   protobuf_AddDesc_x3_2eproto();
 #else
   if (default_instance_ == NULL) protobuf_AddDesc_x3_2eproto();
 #endif
   return *default_instance_;
 }
void x3::Frame::DiscardUnknownFields ()
x3::Frame_FrameType x3::Frame::frame_type_ () const inline
Definition at line 8429 of file x3.pb.h.
Referenced by ByteSize(), MergeFrom(), and SerializeWithCachedSizes().
{
   // @@protoc_insertion_point(field_get:x3.Frame.frame_type_)
   return static_cast< ::x3::Frame_FrameType >(frame_type__);
 }