XStream Framework API Document: xstream Namespace Reference
xstream Namespace Reference
default method factory
Namespaces
method_factory
Classes
struct MethodInfo
Method info The MethodInfo structure defines the attribute information of the Method, including: is_thread_safe_: Indicates whether the Method is thread safe, the default value is false. When defining Workflow, it supports configuring the number of Node threads. If the number of threads is configured to be greater than 1, if the method calculation process is not thread-safe, multiple Method instances will be defined under multithreading; otherwise, multiple threads will reuse one Method instance. is_need_reorder_: Indicate whether the data is required to call Method processing frame by frame in sequence. For example, some target tracking scenarios require the output data to be orderly. The default is false, which means that order is not required. Note: In the method of is_need_reorder_=true, the number of threads is only allowed to be 1 due to the dependency of the front and rear frame order. At the same time, is_need_reorder_=true will reduce the execution efficiency to a certain extent. is_src_ctx_dept_: Indicates whether the processing of input data depends on the input source. For example, in a target tracking scene, the previous few frames of data will be recorded and track_id will be assigned. This type of method needs to set the attribute to is_src_ctx_dept_ = true.
class Method
struct FpsStatisticInfo
struct TimeStatisticInfo
class Profiler
class ProfilerScope
class ScopeTime
class ScopeFps
class SimpleMethod
struct ImageFrame
struct RawDataImageFrame
struct PyramidAddrInfo
struct PyramidImageInfo
struct PyramidImageFrame
struct OriginalPyramidImageFrame
struct DataArray_
struct Attribute_
struct Point_
struct Point3D_
struct Points_
struct BBox_
struct Segmentation
struct Pose3D
struct Age
struct ParkingBBox
struct SnapshotInfo_
struct BaseData
The BaseData structure describes the basic information of the workflow within the framework. The data passed between methods must be derived from BaseData. BaseData data members including: type_: Descriptive information of user-defined data, such as "box", etc. This field currently has no special purpose and can be ignored. name_: The alias of the data. When the framework is running, the name_ of the data is assigned to the name configured in the workflow configuration file. For InputData, the name_ of the externally specified data is required, and the specified name_ needs to be consistent with the name configured in the workflow configuration. error_code_: error_code_. error_detail_: Error information deatail c_data_: context of C structure. It can be ignored. state_: Describe the state of the data, default value is VALID.
struct BaseDataVector
BaseDataVector is a derived class of BaseData, used to represent array data, such as saving all body bbox in a frame of image, each element in the datas_ array points to a body bbox data. datas_: Used to save each value in the array.
class InputParam
InputParam is the data structure of the input data parameter. including: unique_name_: Indicates the unique identifier that this parameter acts on a specific node, corresponding to the Method name in the workflow configuration. is_json_format_: Indicates whether the input parameter is a json string. If it is true, you can get the json string through the Format() interface. is_enable_this_method_: Indicates whether to enable the node. If it is true, this parameter is passed into the node, and the node operates normally; if it is false, the node operation is skipped. Note:When preparing InputData, you can update the configuration parameters of Method through InputParam. Users can inherit this class, define specific parameter types, and then the related Method uses the newly defined data type to parse the configuration parameters.
struct InputData
The InputData structure describes the basic information of the frame's input data flow. Including: datas_: The BaseData array represents the data input for one frame. params_: Input Param array, note that there is no positional correspondence between parameter params_ and input data datas_. There are data members in InputParam that describe which Method the InputParam configuration corresponds to. source_id_: Input source number, which indicates the unique identification of the input source. Multiple input sources are numbered starting from 0, and the single input source defaults to 0. source_id_ is used to support multiple channels. context_: Transparent transmission of data, the data will be transparently transmitted to OutputData, which can be used for special needs.
struct OutputData
The OutputData structure describes the basic information of the output data stream of the framework. including: error_code_: Error code, non-zero means that the prediction is error. error_detail_: Error information description. unique_name_: the output data of a specific node, and unique_name_ corresponds to the name of the Method that generated the data in the workflow configuration. output_type_: The name of the group of output data in multiple output, the default is "NODE_WHOLE_OUTPUT" for single output. datas_: all datas of one frame prediction. context_: Transparent transmission field, which is passed in by the input data InputData.context_ of the frame data. sequence_id_: The output data corresponds to the sequence number of the input frame of the input source, starting from 0 and accumulating sequentially. source_id_: Input source number, which indicates the unique identification of the input source. Multiple input sources are numbered starting from 0, and the single input source defaults to 0. source_id_ is used to support multiple channels. global_sequence_id_: In the case of multiple input sources, it corresponds to the total sequence number of the input frame; in the case of single input source, it is the same as sequence_id_.
class DisableParam
pre-difined param for method
class SdkCommParam
SdkCommParam inherits from InputParam, and describes parameters in json. Get the json string by calling the Format().
class XStreamSDK
XStream API.
Typedefs
typedef std::shared_ptr< Method > MethodPtr
typedef std::shared_ptr< Profiler > ProfilerPtr
typedef std::shared_ptr
< SimpleMethod > SimpleMethodPtr
typedef DataArray_< float > FloatFeature
typedef DataArray_< char > CharEncryptedFeature
typedef Attribute_< int32_t > Gender
typedef Attribute_< int32_t > Glass
typedef Attribute_< int32_t > Quality
typedef Attribute_< int32_t > AntiSpoofing
typedef Attribute_< int32_t > BreathingMask
typedef Attribute_< int32_t > Classification
typedef Attribute_< int32_t > PlateNum
typedef Point_< float > Point
typedef Point3D_< float > Point3D
typedef Points_< float > Landmarks
typedef Points_< float > FloatPoints
typedef BBox_< float > BBox
typedef std::shared_ptr< BBox > BBoxPtr
typedef std::shared_ptr< BaseData > BaseDataPtr
typedef std::shared_ptr
< InputParam > InputParamPtr
typedef std::shared_ptr
< InputData > InputDataPtr
typedef std::shared_ptr
< OutputData > OutputDataPtr
typedef std::function< void(OutputDataPtr)> XStreamCallback
callback func
typedef std::shared_ptr
< DisableParam > DisableParamPtr
typedef std::shared_ptr
< SdkCommParam > CommParamPtr
Enumerations
enum DataState {
DataState::VALID = 0, DataState::FILTERED = 1, DataState::INVISIBLE = 2, DataState::DISAPPEARED = 3,
DataState::INVALID = 4
}
Functions
std::int64_t getMicroSecond ()
Detailed Description
default method factory
Copyright (c) 2020 Horizon Robotics. All rights reserved.
Author
zhuoran.rong zhuor.nosp@m.an.r.nosp@m.ong@h.nosp@m.oriz.nosp@m.on.ai
Version
0.0.0.1
Date
2020.04.15 2021.01.27 by hangjun.yang
Typedef Documentation
typedef Attribute_<int32_t> xstream::AntiSpoofing
Definition at line 385 of file vision_type.h.
typedef std::shared_ptr<BaseData> xstream::BaseDataPtr
Definition at line 72 of file xstream_data.h.
typedef BBox_<float> xstream::BBox
Definition at line 503 of file vision_type.h.
typedef std::shared_ptr<BBox> xstream::BBoxPtr
Definition at line 504 of file vision_type.h.
typedef Attribute_<int32_t> xstream::BreathingMask
Definition at line 386 of file vision_type.h.
typedef DataArray_<char> xstream::CharEncryptedFeature
Definition at line 357 of file vision_type.h.
typedef Attribute_<int32_t> xstream::Classification
Definition at line 387 of file vision_type.h.
typedef std::shared_ptr<SdkCommParam> xstream::CommParamPtr
Definition at line 245 of file xstream_data.h.
typedef std::shared_ptr<DisableParam> xstream::DisableParamPtr
Definition at line 225 of file xstream_data.h.
typedef DataArray_<float> xstream::FloatFeature
Definition at line 356 of file vision_type.h.
typedef Points_<float> xstream::FloatPoints
Definition at line 463 of file vision_type.h.
typedef Attribute_<int32_t> xstream::Gender
Definition at line 382 of file vision_type.h.
typedef Attribute_<int32_t> xstream::Glass
Definition at line 383 of file vision_type.h.
typedef std::shared_ptr<InputData> xstream::InputDataPtr
Definition at line 144 of file xstream_data.h.
typedef std::shared_ptr<InputParam> xstream::InputParamPtr
Definition at line 118 of file xstream_data.h.
typedef Points_<float> xstream::Landmarks
Definition at line 462 of file vision_type.h.
typedef std::shared_ptr<Method> xstream::MethodPtr
Definition at line 122 of file method.h.
typedef std::shared_ptr<OutputData> xstream::OutputDataPtr
Definition at line 186 of file xstream_data.h.
typedef Attribute_<int32_t> xstream::PlateNum
Definition at line 389 of file vision_type.h.
typedef Point_<float> xstream::Point
Definition at line 410 of file vision_type.h.
typedef Point3D_<float> xstream::Point3D
Definition at line 442 of file vision_type.h.
typedef std::shared_ptr<Profiler> xstream::ProfilerPtr
Definition at line 54 of file profiler.h.
typedef Attribute_<int32_t> xstream::Quality
Definition at line 384 of file vision_type.h.
typedef std::shared_ptr<SimpleMethod> xstream::SimpleMethodPtr
Definition at line 103 of file simple_method.h.
typedef std::function<void(OutputDataPtr)> xstream::XStreamCallback
callback func
Definition at line 189 of file xstream_data.h.
Enumeration Type Documentation
enum xstream::DataState strong
DataState defines several basic states of data. In the process of development, data processing may rely on these states. If the data is normally valid, it should be set to VALID.
Enumerator
VALID
valid
FILTERED
filtered
INVISIBLE
invisible
DISAPPEARED
disappeared
INVALID
invalid
Definition at line 29 of file xstream_data.h.
                      {
   VALID = 0,
   FILTERED = 1,
   INVISIBLE = 2,
   DISAPPEARED = 3,
   INVALID = 4,
 };
Function Documentation
std::int64_t xstream::getMicroSecond () inline
Definition at line 28 of file profiler.h.
Referenced by xstream::ScopeFps::ScopeFps(), xstream::ScopeTime::ScopeTime(), xstream::ScopeFps::~ScopeFps(), and xstream::ScopeTime::~ScopeTime().
{
   auto time_now = std::chrono::system_clock::now();
   auto duration_in_ms = std::chrono::duration_cast<std::chrono::microseconds>(
       time_now.time_since_epoch());